export interface Product {
  id: string
  name: string
  category: 'shoes' | 'clothing' | 'accessories' | 'equipment'
  subcategory: string
  price: number
  originalPrice?: number
  description: string
  longDescription: string
  images: string[]
  thumbnail: string
  gender: 'men' | 'women' | 'unisex'

  sizes: string[]
  sizeChart?: string

  colors: { name: string; hex: string; sku: string }[]

  material: string
  details: string[]
  features: string[]

  stock: number
  stockStatus: 'in-stock' | 'low-stock' | 'pre-order' | 'out-of-stock'

  discount?: number
  badge?: 'new' | 'bestseller' | 'sale' | 'limited'

  rating: number
  reviewCount: number

  slug: string
  aliexpressUrl?: string // AliExpress product link
}

export const products: Product[] = [
  // ========== RUNNING SHOES (10 products) ==========
  {
    id: 'shoe-run-001',
    name: 'Quantum Flow Pro Running Shoe',
    category: 'shoes',
    subcategory: 'running',
    price: 45.99,
    originalPrice: 89.99,
    description: 'Professional running shoe with responsive foam cushioning and breathable mesh',
    longDescription: 'Experience maximum performance with responsive Quantum foam technology, engineered for speed and comfort. Features breathable mesh upper, durable rubber outsole, and anatomical design for optimal foot support during long-distance runs.',
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&h=800&fit=crop'],
    thumbnail: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=200&h=200&fit=crop',
    gender: 'men',
    sizes: ['35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46'],
    colors: [
      { name: 'Black', hex: '#000000', sku: 'QFP-BLK-001' },
      { name: 'White', hex: '#FFFFFF', sku: 'QFP-WHT-001' },
      { name: 'Navy Blue', hex: '#001f3f', sku: 'QFP-NVY-001' },
      { name: 'Red', hex: '#FF4136', sku: 'QFP-RED-001' },
      { name: 'Gray', hex: '#999999', sku: 'QFP-GRY-001' },
    ],
    material: 'Mesh upper, EVA foam midsole, Rubber outsole',
    details: ['Weight: 210g', 'Drop: 10mm', 'Breathable mesh'],
    features: ['Ultra-lightweight', 'Responsive cushioning', 'Anti-slip traction', 'Anatomical design'],
    stock: 120,
    stockStatus: 'in-stock',
    discount: 49,
    badge: 'bestseller',
    rating: 4.8,
    reviewCount: 2847,
    slug: 'quantum-flow-pro-running-shoe',
    aliexpressUrl: 'https://aliexpress.com/item/[ADD-YOUR-LINK]',
  },
  {
    id: 'shoe-run-002',
    name: 'AeroMax Sprint Performance Running Shoe',
    category: 'shoes',
    subcategory: 'running',
    price: 52.99,
    originalPrice: 99.99,
    description: 'High-performance sprint shoe with aerodynamic design and maximum grip',
    longDescription: 'Designed for competitive runners, the AeroMax Sprint features aerodynamic silhouette, superior grip technology, and lightweight construction. Perfect for track, road, or treadmill training with optimal energy return.',
    images: ['https://images.unsplash.com/photo-1460353581641-a1af1d3ba3c1?w=800&h=800&fit=crop'],
    thumbnail: 'https://images.unsplash.com/photo-1460353581641-a1af1d3ba3c1?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46'],
    colors: [
      { name: 'Black', hex: '#000000', sku: 'AMS-BLK-001' },
      { name: 'White', hex: '#FFFFFF', sku: 'AMS-WHT-001' },
      { name: 'Electric Blue', hex: '#0066FF', sku: 'AMS-BLU-001' },
      { name: 'Lime Green', hex: '#00FF00', sku: 'AMS-GRN-001' },
    ],
    material: 'Engineered mesh, Responsive foam, Carbon rubber',
    details: ['Weight: 195g', 'Drop: 8mm', 'Aerodynamic design'],
    features: ['Speed-focused design', 'Superior grip', 'Energy return', 'Lightweight'],
    stock: 95,
    stockStatus: 'in-stock',
    discount: 47,
    badge: 'bestseller',
    rating: 4.7,
    reviewCount: 2156,
    slug: 'aeromax-sprint-performance-running-shoe',
    aliexpressUrl: 'https://aliexpress.com/item/[ADD-YOUR-LINK]',
  },
  {
    id: 'shoe-run-003',
    name: 'TrailBlazer X Outdoor Running Shoe',
    category: 'shoes',
    subcategory: 'running',
    price: 58.99,
    originalPrice: 119.99,
    description: 'Trail-specific running shoe with aggressive tread and superior stability',
    longDescription: 'Conquer any terrain with TrailBlazer X. Features aggressive tread pattern for off-road traction, reinforced ankle support, and rugged outsole. Ideal for trail running, hiking, and outdoor adventures.',
    images: ['https://images.unsplash.com/photo-1549622328-ace0f0cc2eb4?w=800&h=800&fit=crop'],
    thumbnail: 'https://images.unsplash.com/photo-1549622328-ace0f0cc2eb4?w=200&h=200&fit=crop',
    gender: 'men',
    sizes: ['35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46'],
    colors: [
      { name: 'Trail Brown', hex: '#8B4513', sku: 'TBX-BRN-001' },
      { name: 'Forest Green', hex: '#228B22', sku: 'TBX-GRN-001' },
      { name: 'Gray', hex: '#808080', sku: 'TBX-GRY-001' },
      { name: 'Black', hex: '#000000', sku: 'TBX-BLK-001' },
    ],
    material: 'Reinforced mesh, Trail-rated midsole, Aggressive rubber outsole',
    details: ['Weight: 245g', 'Drop: 12mm', 'Ankle support'],
    features: ['Aggressive tread', 'Trail-rated', 'Ankle reinforcement', 'Outdoor durability'],
    stock: 78,
    stockStatus: 'in-stock',
    discount: 51,
    badge: 'new',
    rating: 4.6,
    reviewCount: 1923,
    slug: 'trailblazer-x-outdoor-running-shoe',
    aliexpressUrl: 'https://aliexpress.com/item/[ADD-YOUR-LINK]',
  },
  {
    id: 'shoe-run-004',
    name: 'UltraComfort Marathon Running Shoe',
    category: 'shoes',
    subcategory: 'running',
    price: 49.99,
    originalPrice: 109.99,
    description: 'Maximum cushioning for long-distance marathon running',
    longDescription: 'The ultimate marathon companion with maximum cushioning and support. UltraComfort features multi-layered foam technology, gel inserts, and supportive arch design for marathon distances and beyond.',
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&h=800&fit=crop'],
    thumbnail: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=200&h=200&fit=crop',
    gender: 'women',
    sizes: ['34', '35', '36', '37', '38', '39', '40', '41', '42', '43'],
    colors: [
      { name: 'Rose Pink', hex: '#FF69B4', sku: 'UCM-RSE-001' },
      { name: 'Lavender', hex: '#E6E6FA', sku: 'UCM-LAV-001' },
      { name: 'White', hex: '#FFFFFF', sku: 'UCM-WHT-001' },
      { name: 'Purple', hex: '#9933CC', sku: 'UCM-PUR-001' },
    ],
    material: 'Premium mesh, Multi-layer foam, Gel inserts',
    details: ['Weight: 260g', 'Drop: 12mm', 'Gel cushioning'],
    features: ['Maximum comfort', 'Marathon-ready', 'Arch support', 'Impact absorption'],
    stock: 102,
    stockStatus: 'in-stock',
    discount: 54,
    badge: 'bestseller',
    rating: 4.9,
    reviewCount: 3421,
    slug: 'ultracomfort-marathon-running-shoe',
    aliexpressUrl: 'https://aliexpress.com/item/[ADD-YOUR-LINK]',
  },
  {
    id: 'shoe-run-005',
    name: 'SpeedWave Track Racing Shoe',
    category: 'shoes',
    subcategory: 'running',
    price: 54.99,
    originalPrice: 129.99,
    description: 'Lightweight track racing shoe for competitive athletes',
    longDescription: 'Purpose-built for track competition. SpeedWave features minimal weight design, stiff midsole for energy efficiency, and aggressive tread for track surface. Ideal for sprints, middle distance, and competitive training.',
    images: ['https://images.unsplash.com/photo-1460353581641-a1af1d3ba3c1?w=800&h=800&fit=crop'],
    thumbnail: 'https://images.unsplash.com/photo-1460353581641-a1af1d3ba3c1?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46'],
    colors: [
      { name: 'Gold', hex: '#FFD700', sku: 'SWT-GLD-001' },
      { name: 'Silver', hex: '#C0C0C0', sku: 'SWT-SLV-001' },
      { name: 'Black', hex: '#000000', sku: 'SWT-BLK-001' },
    ],
    material: 'Carbon fiber mesh, Stiff midsole, Track spike compatible',
    details: ['Weight: 165g', 'Drop: 7mm', 'Minimal design'],
    features: ['Track-optimized', 'Energy efficient', 'Competition-ready', 'Ultra-light'],
    stock: 56,
    stockStatus: 'in-stock',
    discount: 58,
    badge: 'sale',
    rating: 4.7,
    reviewCount: 1678,
    slug: 'speedwave-track-racing-shoe',
    aliexpressUrl: 'https://aliexpress.com/item/[ADD-YOUR-LINK]',
  },
  {
    id: 'shoe-run-006',
    name: 'CloudStep Comfort Everyday Running Shoe',
    category: 'shoes',
    subcategory: 'running',
    price: 43.99,
    originalPrice: 84.99,
    description: 'Versatile everyday running shoe for casual and training use',
    longDescription: 'Perfect for daily training and casual running. CloudStep combines comfort, durability, and style with cloud-like cushioning, breathable materials, and modern aesthetics.',
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&h=800&fit=crop'],
    thumbnail: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46'],
    colors: [
      { name: 'Cloud White', hex: '#F0F8FF', sku: 'CSC-WHT-001' },
      { name: 'Sky Gray', hex: '#B0C4DE', sku: 'CSC-GRY-001' },
      { name: 'Deep Navy', hex: '#00008B', sku: 'CSC-NVY-001' },
      { name: 'Ocean Blue', hex: '#006994', sku: 'CSC-BLU-001' },
    ],
    material: 'Soft mesh, Cloud foam cushioning, Flexible outsole',
    details: ['Weight: 225g', 'Drop: 10mm', 'All-day comfort'],
    features: ['Cloud cushioning', 'Versatile style', 'Breathable mesh', 'Durable construction'],
    stock: 145,
    stockStatus: 'in-stock',
    discount: 48,
    badge: 'bestseller',
    rating: 4.6,
    reviewCount: 2534,
    slug: 'cloudstep-comfort-everyday-running-shoe',
    aliexpressUrl: 'https://aliexpress.com/item/[ADD-YOUR-LINK]',
  },
  {
    id: 'shoe-run-007',
    name: 'VortexPace Training Running Shoe',
    category: 'shoes',
    subcategory: 'running',
    price: 47.99,
    originalPrice: 99.99,
    description: 'Advanced training shoe with integrated stability technology',
    longDescription: 'Designed for serious trainers. VortexPace features integrated stability technology, responsive midsole, and superior traction. Excellent for interval training, tempo runs, and structured workouts.',
    images: ['https://images.unsplash.com/photo-1460353581641-a1af1d3ba3c1?w=800&h=800&fit=crop'],
    thumbnail: 'https://images.unsplash.com/photo-1460353581641-a1af1d3ba3c1?w=200&h=200&fit=crop',
    gender: 'men',
    sizes: ['35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46'],
    colors: [
      { name: 'Vortex Black', hex: '#1A1A1A', sku: 'VTP-BLK-001' },
      { name: 'Electric Orange', hex: '#FF8C00', sku: 'VTP-ORN-001' },
      { name: 'Cyan', hex: '#00FFFF', sku: 'VTP-CYN-001' },
    ],
    material: 'Structured mesh, Stability foam, Reinforced midsole',
    details: ['Weight: 230g', 'Drop: 10mm', 'Stability support'],
    features: ['Stability technology', 'Responsive feel', 'Training optimized', 'Structured fit'],
    stock: 88,
    stockStatus: 'in-stock',
    discount: 52,
    badge: 'new',
    rating: 4.5,
    reviewCount: 1845,
    slug: 'vortexpace-training-running-shoe',
    aliexpressUrl: 'https://aliexpress.com/item/[ADD-YOUR-LINK]',
  },
  {
    id: 'shoe-run-008',
    name: 'NimbusFlow Cross-Training Running Shoe',
    category: 'shoes',
    subcategory: 'running',
    price: 51.99,
    originalPrice: 109.99,
    description: 'Versatile cross-training shoe for multiple athletic activities',
    longDescription: 'NimbusFlow is your all-purpose athletic shoe. Perfect for running, gym training, and cross-training with multi-directional traction, lateral support, and cushioning that adapts to any activity.',
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&h=800&fit=crop'],
    thumbnail: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=200&h=200&fit=crop',
    gender: 'women',
    sizes: ['34', '35', '36', '37', '38', '39', '40', '41', '42', '43'],
    colors: [
      { name: 'Coral Pink', hex: '#FF7F50', sku: 'NFC-COR-001' },
      { name: 'Mint Green', hex: '#98FF98', sku: 'NFC-MNT-001' },
      { name: 'Royal Purple', hex: '#7851A9', sku: 'NFC-PUR-001' },
      { name: 'Black', hex: '#000000', sku: 'NFC-BLK-001' },
    ],
    material: 'Premium mesh, Multi-cushion foam, Directional outsole',
    details: ['Weight: 235g', 'Drop: 10mm', 'Cross-training ready'],
    features: ['Multi-directional traction', 'Lateral support', 'Versatile cushioning', 'All-activity ready'],
    stock: 110,
    stockStatus: 'in-stock',
    discount: 53,
    badge: 'bestseller',
    rating: 4.7,
    reviewCount: 2289,
    slug: 'nimbusflow-cross-training-running-shoe',
    aliexpressUrl: 'https://aliexpress.com/item/[ADD-YOUR-LINK]',
  },
  {
    id: 'shoe-run-009',
    name: 'PeakPerformance Ultra Marathon Shoe',
    category: 'shoes',
    subcategory: 'running',
    price: 63.99,
    originalPrice: 139.99,
    description: 'Ultimate ultra-marathon shoe with maximum durability and comfort',
    longDescription: 'For the ultimate distance runner. PeakPerformance combines maximum cushioning, exceptional durability, and lightweight design specifically engineered for ultra-marathon distances and beyond.',
    images: ['https://images.unsplash.com/photo-1460353581641-a1af1d3ba3c1?w=800&h=800&fit=crop'],
    thumbnail: 'https://images.unsplash.com/photo-1460353581641-a1af1d3ba3c1?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46'],
    colors: [
      { name: 'Summit White', hex: '#FFFAFA', sku: 'PPU-WHT-001' },
      { name: 'Mountain Gray', hex: '#696969', sku: 'PPU-GRY-001' },
      { name: 'Trail Black', hex: '#000000', sku: 'PPU-BLK-001' },
    ],
    material: 'Ultra-durable mesh, Multi-layer foam, Reinforced outsole',
    details: ['Weight: 270g', 'Drop: 12mm', 'Ultra-durable'],
    features: ['Ultra-marathon ready', 'Maximum durability', 'Enhanced comfort', 'Long-distance optimized'],
    stock: 64,
    stockStatus: 'in-stock',
    discount: 54,
    badge: 'limited',
    rating: 4.8,
    reviewCount: 892,
    slug: 'peakperformance-ultra-marathon-shoe',
    aliexpressUrl: 'https://aliexpress.com/item/[ADD-YOUR-LINK]',
  },
  {
    id: 'shoe-run-010',
    name: 'SwiftStep Speed Running Shoe',
    category: 'shoes',
    subcategory: 'running',
    price: 46.99,
    originalPrice: 94.99,
    description: 'Speed-focused running shoe for tempo and pace training',
    longDescription: 'Built for speed enthusiasts. SwiftStep features a balanced design combining lightweight construction, responsive cushioning, and optimal ground feel for tempo runs and pace training.',
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&h=800&fit=crop'],
    thumbnail: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=200&h=200&fit=crop',
    gender: 'men',
    sizes: ['35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46'],
    colors: [
      { name: 'Jet Black', hex: '#1C1C1C', sku: 'SWS-BLK-001' },
      { name: 'Speed Red', hex: '#DC143C', sku: 'SWS-RED-001' },
      { name: 'Power White', hex: '#FFFFFF', sku: 'SWS-WHT-001' },
    ],
    material: 'Speed mesh, Responsive foam, Lightweight outsole',
    details: ['Weight: 205g', 'Drop: 9mm', 'Speed optimized'],
    features: ['Speed-focused', 'Responsive cushioning', 'Lightweight design', 'Optimal ground feel'],
    stock: 125,
    stockStatus: 'in-stock',
    discount: 50,
    badge: 'bestseller',
    rating: 4.6,
    reviewCount: 1956,
    slug: 'swiftstep-speed-running-shoe',
    aliexpressUrl: 'https://aliexpress.com/item/[ADD-YOUR-LINK]',
  },

  // ========== BASKETBALL SHOES (8 products) ==========
  {
    id: 'shoe-bask-001',
    name: 'DunkMaster Pro Basketball Shoe',
    category: 'shoes',
    subcategory: 'basketball',
    price: 68.99,
    originalPrice: 159.99,
    description: 'Professional basketball shoe with ankle support and jump technology',
    longDescription: 'Designed for court dominance. DunkMaster Pro features advanced ankle support system, impact-absorbing cushioning, and optimal traction for explosive movements on the court.',
    images: ['https://images.unsplash.com/photo-1539038919170-14bc4e45c047?w=800&h=800&fit=crop'],
    thumbnail: 'https://images.unsplash.com/photo-1539038919170-14bc4e45c047?w=200&h=200&fit=crop',
    gender: 'men',
    sizes: ['35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46'],
    colors: [
      { name: 'Court Black', hex: '#000000', sku: 'DMP-BLK-001' },
      { name: 'Team Red', hex: '#CC0000', sku: 'DMP-RED-001' },
      { name: 'Gold', hex: '#FFD700', sku: 'DMP-GLD-001' },
      { name: 'Navy', hex: '#001f3f', sku: 'DMP-NVY-001' },
    ],
    material: 'Synthetic leather, Memory foam, Rubber court outsole',
    details: ['Height: Mid-top', 'Ankle support: Advanced', 'Court traction: Superior'],
    features: ['Ankle support system', 'Impact absorption', 'Court traction', 'Jump technology'],
    stock: 76,
    stockStatus: 'in-stock',
    discount: 57,
    badge: 'bestseller',
    rating: 4.8,
    reviewCount: 2134,
    slug: 'dunkmaster-pro-basketball-shoe',
    aliexpressUrl: 'https://aliexpress.com/item/[ADD-YOUR-LINK]',
  },
  {
    id: 'shoe-bask-002',
    name: 'CourtKing Elite Basketball Shoe',
    category: 'shoes',
    subcategory: 'basketball',
    price: 72.99,
    originalPrice: 169.99,
    description: 'Elite basketball shoe for professional and serious players',
    longDescription: 'CourtKing Elite is engineered for elite athletes. Features premium materials, advanced ankle stability, cushioning technology, and court-specific traction for competitive basketball.',
    images: ['https://images.unsplash.com/photo-1539038919170-14bc4e45c047?w=800&h=800&fit=crop'],
    thumbnail: 'https://images.unsplash.com/photo-1539038919170-14bc4e45c047?w=200&h=200&fit=crop',
    gender: 'men',
    sizes: ['35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46'],
    colors: [
      { name: 'Premium Black', hex: '#000000', sku: 'CKE-BLK-001' },
      { name: 'Championship Gold', hex: '#FFD700', sku: 'CKE-GLD-001' },
      { name: 'Royal Purple', hex: '#7851A9', sku: 'CKE-PUR-001' },
    ],
    material: 'Premium synthetic, Gel cushioning, Professional outsole',
    details: ['Height: Mid-top', 'Ankle support: Premium', 'Court traction: Professional'],
    features: ['Elite performance', 'Gel cushioning', 'Premium materials', 'Professional traction'],
    stock: 54,
    stockStatus: 'in-stock',
    discount: 57,
    badge: 'new',
    rating: 4.9,
    reviewCount: 1567,
    slug: 'courtking-elite-basketball-shoe',
    aliexpressUrl: 'https://aliexpress.com/item/[ADD-YOUR-LINK]',
  },
  {
    id: 'shoe-bask-003',
    name: 'SlamJam High-Top Basketball Shoe',
    category: 'shoes',
    subcategory: 'basketball',
    price: 64.99,
    originalPrice: 139.99,
    description: 'High-top basketball shoe with enhanced ankle stability',
    longDescription: 'SlamJam combines high-top design with enhanced ankle stability and comfort. Perfect for players who need maximum support and want to make an impact on the court.',
    images: ['https://images.unsplash.com/photo-1539038919170-14bc4e45c047?w=800&h=800&fit=crop'],
    thumbnail: 'https://images.unsplash.com/photo-1539038919170-14bc4e45c047?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46'],
    colors: [
      { name: 'Slam Black', hex: '#000000', sku: 'SJH-BLK-001' },
      { name: 'Energy Red', hex: '#FF0000', sku: 'SJH-RED-001' },
      { name: 'Storm Gray', hex: '#808080', sku: 'SJH-GRY-001' },
      { name: 'Ocean Blue', hex: '#0077BE', sku: 'SJH-BLU-001' },
    ],
    material: 'Synthetic leather, Foam cushioning, Anti-slip outsole',
    details: ['Height: High-top', 'Ankle support: Enhanced', 'Court traction: Excellent'],
    features: ['High-top stability', 'Ankle support', 'Comfortable fit', 'Court traction'],
    stock: 89,
    stockStatus: 'in-stock',
    discount: 54,
    badge: 'bestseller',
    rating: 4.7,
    reviewCount: 1823,
    slug: 'slamjam-high-top-basketball-shoe',
    aliexpressUrl: 'https://aliexpress.com/item/[ADD-YOUR-LINK]',
  },
  {
    id: 'shoe-bask-004',
    name: 'FastBreak Lightweight Basketball Shoe',
    category: 'shoes',
    subcategory: 'basketball',
    price: 59.99,
    originalPrice: 129.99,
    description: 'Lightweight basketball shoe for speed and agility',
    longDescription: 'FastBreak prioritizes speed and agility on the court. Lightweight construction combined with responsive cushioning and superior court control for quick-moving players.',
    images: ['https://images.unsplash.com/photo-1539038919170-14bc4e45c047?w=800&h=800&fit=crop'],
    thumbnail: 'https://images.unsplash.com/photo-1539038919170-14bc4e45c047?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46'],
    colors: [
      { name: 'Speed White', hex: '#FFFFFF', sku: 'FBL-WHT-001' },
      { name: 'Quick Black', hex: '#000000', sku: 'FBL-BLK-001' },
      { name: 'Flash Yellow', hex: '#FFFF00', sku: 'FBL-YEL-001' },
    ],
    material: 'Lightweight mesh, Responsive foam, Thin rubber outsole',
    details: ['Height: Mid-top', 'Weight: Lightweight', 'Court feel: Responsive'],
    features: ['Lightweight design', 'Responsive cushioning', 'Court control', 'Speed optimized'],
    stock: 98,
    stockStatus: 'in-stock',
    discount: 54,
    badge: 'sale',
    rating: 4.6,
    reviewCount: 1534,
    slug: 'fastbreak-lightweight-basketball-shoe',
    aliexpressUrl: 'https://aliexpress.com/item/[ADD-YOUR-LINK]',
  },
  {
    id: 'shoe-bask-005',
    name: 'BlockShot Defense Basketball Shoe',
    category: 'shoes',
    subcategory: 'basketball',
    price: 66.99,
    originalPrice: 149.99,
    description: 'Defensive-focused basketball shoe with wide base and stability',
    longDescription: 'BlockShot is designed for defensive players. Features wide stance base, enhanced lateral support, and reinforced structure for stopping and pivoting movements.',
    images: ['https://images.unsplash.com/photo-1539038919170-14bc4e45c047?w=800&h=800&fit=crop'],
    thumbnail: 'https://images.unsplash.com/photo-1539038919170-14bc4e45c047?w=200&h=200&fit=crop',
    gender: 'men',
    sizes: ['35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46'],
    colors: [
      { name: 'Defense Black', hex: '#000000', sku: 'BSD-BLK-001' },
      { name: 'Defensive Green', hex: '#006B3F', sku: 'BSD-GRN-001' },
      { name: 'Guardian Gray', hex: '#505050', sku: 'BSD-GRY-001' },
    ],
    material: 'Reinforced synthetic, Wide base cushioning, Stability outsole',
    details: ['Height: Mid-top', 'Base: Wide', 'Lateral support: Strong'],
    features: ['Defensive stability', 'Wide base', 'Lateral support', 'Reinforced structure'],
    stock: 71,
    stockStatus: 'in-stock',
    discount: 55,
    badge: 'new',
    rating: 4.5,
    reviewCount: 1289,
    slug: 'blockshot-defense-basketball-shoe',
    aliexpressUrl: 'https://aliexpress.com/item/[ADD-YOUR-LINK]',
  },
  {
    id: 'shoe-bask-006',
    name: 'ThreePoint Shooter Basketball Shoe',
    category: 'shoes',
    subcategory: 'basketball',
    price: 61.99,
    originalPrice: 139.99,
    description: 'Balanced basketball shoe for shooters and all-around players',
    longDescription: 'ThreePoint offers balanced performance for shooters. Optimal comfort, responsive feel, and court control for players who shoot from anywhere on the court.',
    images: ['https://images.unsplash.com/photo-1539038919170-14bc4e45c047?w=800&h=800&fit=crop'],
    thumbnail: 'https://images.unsplash.com/photo-1539038919170-14bc4e45c047?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46'],
    colors: [
      { name: 'Shot White', hex: '#FFFFFF', sku: 'TPS-WHT-001' },
      { name: 'Range Black', hex: '#000000', sku: 'TPS-BLK-001' },
      { name: 'Court Gray', hex: '#A9A9A9', sku: 'TPS-GRY-001' },
      { name: 'Target Blue', hex: '#0099FF', sku: 'TPS-BLU-001' },
    ],
    material: 'Comfort mesh, Responsive cushioning, Court outsole',
    details: ['Height: Mid-top', 'Feel: Responsive', 'Comfort: Premium'],
    features: ['Balanced performance', 'Responsive feel', 'Comfort focused', 'All-around play'],
    stock: 85,
    stockStatus: 'in-stock',
    discount: 56,
    badge: 'bestseller',
    rating: 4.7,
    reviewCount: 1923,
    slug: 'threepoint-shooter-basketball-shoe',
    aliexpressUrl: 'https://aliexpress.com/item/[ADD-YOUR-LINK]',
  },
  {
    id: 'shoe-bask-007',
    name: 'PostGame Recovery Basketball Shoe',
    category: 'shoes',
    subcategory: 'basketball',
    price: 57.99,
    originalPrice: 119.99,
    description: 'Casual basketball shoe for post-game and casual wear',
    longDescription: 'PostGame combines basketball heritage with casual style. Great for wearing after games, casual outings, or everyday comfort with basketball DNA in its design.',
    images: ['https://images.unsplash.com/photo-1539038919170-14bc4e45c047?w=800&h=800&fit=crop'],
    thumbnail: 'https://images.unsplash.com/photo-1539038919170-14bc4e45c047?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46'],
    colors: [
      { name: 'Casual Black', hex: '#000000', sku: 'PGR-BLK-001' },
      { name: 'Relaxed White', hex: '#F5F5F5', sku: 'PGR-WHT-001' },
      { name: 'Chill Gray', hex: '#D3D3D3', sku: 'PGR-GRY-001' },
    ],
    material: 'Soft mesh, Comfort foam, Casual outsole',
    details: ['Height: Low-top', 'Style: Casual', 'Comfort: Maximum'],
    features: ['Casual style', 'Basketball heritage', 'Everyday comfort', 'Lifestyle wear'],
    stock: 110,
    stockStatus: 'in-stock',
    discount: 52,
    badge: 'sale',
    rating: 4.4,
    reviewCount: 1645,
    slug: 'postgame-recovery-basketball-shoe',
    aliexpressUrl: 'https://aliexpress.com/item/[ADD-YOUR-LINK]',
  },
  {
    id: 'shoe-bask-008',
    name: 'JumpMaster Vertical Basketball Shoe',
    category: 'shoes',
    subcategory: 'basketball',
    price: 69.99,
    originalPrice: 159.99,
    description: 'Jump-optimized basketball shoe for explosive vertical movement',
    longDescription: 'JumpMaster is built for athletes who rely on vertical explosiveness. Features spring-loaded heel, responsive midsole, and design specifically engineered to enhance jumping ability.',
    images: ['https://images.unsplash.com/photo-1539038919170-14bc4e45c047?w=800&h=800&fit=crop'],
    thumbnail: 'https://images.unsplash.com/photo-1539038919170-14bc4e45c047?w=200&h=200&fit=crop',
    gender: 'men',
    sizes: ['35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46'],
    colors: [
      { name: 'Sky High', hex: '#00BFFF', sku: 'JMV-BLU-001' },
      { name: 'Jump Black', hex: '#000000', sku: 'JMV-BLK-001' },
      { name: 'Explosive Red', hex: '#FF0000', sku: 'JMV-RED-001' },
    ],
    material: 'Spring-loaded heel, Responsive foam, Pro outsole',
    details: ['Height: Mid-top', 'Jump tech: Spring-loaded', 'Responsiveness: High'],
    features: ['Jump optimization', 'Explosive response', 'Vertical enhancement', 'Spring technology'],
    stock: 62,
    stockStatus: 'in-stock',
    discount: 56,
    badge: 'limited',
    rating: 4.8,
    reviewCount: 987,
    slug: 'jumpmaster-vertical-basketball-shoe',
    aliexpressUrl: 'https://aliexpress.com/item/[ADD-YOUR-LINK]',
  },

  // ========== CASUAL SNEAKERS (8 products) ==========
  {
    id: 'shoe-casual-001',
    name: 'UrbanStyle Classic Sneaker',
    category: 'shoes',
    subcategory: 'casual',
    price: 35.99,
    originalPrice: 79.99,
    description: 'Timeless casual sneaker for everyday urban style',
    longDescription: 'The perfect everyday sneaker. UrbanStyle Classic combines minimalist design with comfort for all-day wear. Works with any outfit from casual to smart-casual.',
    images: ['https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=800&h=800&fit=crop'],
    thumbnail: 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46'],
    colors: [
      { name: 'Classic White', hex: '#FFFFFF', sku: 'USC-WHT-001' },
      { name: 'Urban Black', hex: '#000000', sku: 'USC-BLK-001' },
      { name: 'Gray Neutral', hex: '#808080', sku: 'USC-GRY-001' },
      { name: 'Navy Classic', hex: '#001f3f', sku: 'USC-NVY-001' },
      { name: 'Khaki', hex: '#CCCCCC', sku: 'USC-KHK-001' },
    ],
    material: 'Canvas upper, Rubber sole, Soft lining',
    details: ['Style: Minimalist', 'Comfort: All-day', 'Versatile: Smart-casual ready'],
    features: ['Timeless design', 'All-day comfort', 'Versatile style', 'Everyday essential'],
    stock: 180,
    stockStatus: 'in-stock',
    discount: 55,
    badge: 'bestseller',
    rating: 4.7,
    reviewCount: 3456,
    slug: 'urbanstyle-classic-sneaker',
    aliexpressUrl: 'https://aliexpress.com/item/[ADD-YOUR-LINK]',
  },
  {
    id: 'shoe-casual-002',
    name: 'StreetWalk Leather Casual Sneaker',
    category: 'shoes',
    subcategory: 'casual',
    price: 42.99,
    originalPrice: 94.99,
    description: 'Premium leather casual sneaker with modern design',
    longDescription: 'StreetWalk features premium synthetic leather construction for a sophisticated casual look. Perfect for weekend outings and smart-casual environments.',
    images: ['https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=800&h=800&fit=crop'],
    thumbnail: 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46'],
    colors: [
      { name: 'Premium White', hex: '#F5F5F5', sku: 'SWL-WHT-001' },
      { name: 'Black Leather', hex: '#1C1C1C', sku: 'SWL-BLK-001' },
      { name: 'Tan', hex: '#D2B48C', sku: 'SWL-TAN-001' },
      { name: 'Brown', hex: '#8B4513', sku: 'SWL-BRN-001' },
    ],
    material: 'Premium synthetic leather, Leather lining, Rubber sole',
    details: ['Material: Premium leather', 'Style: Modern casual', 'Quality: High'],
    features: ['Premium leather look', 'Modern design', 'Quality construction', 'Smart-casual ready'],
    stock: 124,
    stockStatus: 'in-stock',
    discount: 55,
    badge: 'new',
    rating: 4.6,
    reviewCount: 1876,
    slug: 'streetwalk-leather-casual-sneaker',
    aliexpressUrl: 'https://aliexpress.com/item/[ADD-YOUR-LINK]',
  },
  {
    id: 'shoe-casual-003',
    name: 'RetroVibe Lifestyle Sneaker',
    category: 'shoes',
    subcategory: 'casual',
    price: 44.99,
    originalPrice: 99.99,
    description: 'Retro-inspired sneaker with modern comfort technology',
    longDescription: 'RetroVibe brings back classic sneaker aesthetics with modern comfort. Inspired by 80s and 90s design with contemporary cushioning and materials.',
    images: ['https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=800&h=800&fit=crop'],
    thumbnail: 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46'],
    colors: [
      { name: 'Retro White', hex: '#FFFFFF', sku: 'RVL-WHT-001' },
      { name: 'Retro Black', hex: '#000000', sku: 'RVL-BLK-001' },
      { name: 'Vintage Red', hex: '#CD5C5C', sku: 'RVL-RED-001' },
      { name: 'Retro Blue', hex: '#4169E1', sku: 'RVL-BLU-001' },
      { name: 'Cream', hex: '#FFFDD0', sku: 'RVL-CRM-001' },
    ],
    material: 'Suede/Canvas blend, Memory foam, Vintage-style sole',
    details: ['Style: Retro', 'Comfort: Modern', 'Aesthetic: Vintage-inspired'],
    features: ['Retro design', 'Modern comfort', '80s/90s inspired', 'Lifestyle ready'],
    stock: 96,
    stockStatus: 'in-stock',
    discount: 55,
    badge: 'bestseller',
    rating: 4.8,
    reviewCount: 2234,
    slug: 'retrovibe-lifestyle-sneaker',
    aliexpressUrl: 'https://aliexpress.com/item/[ADD-YOUR-LINK]',
  },
  {
    id: 'shoe-casual-004',
    name: 'MinimalChic Slip-On Sneaker',
    category: 'shoes',
    subcategory: 'casual',
    price: 38.99,
    originalPrice: 84.99,
    description: 'Minimalist slip-on sneaker for maximum convenience',
    longDescription: 'MinimalChic prioritizes convenience without sacrificing style. Easy slip-on design, minimalist aesthetics, and all-day comfort for busy lifestyles.',
    images: ['https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=800&h=800&fit=crop'],
    thumbnail: 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46'],
    colors: [
      { name: 'Slip White', hex: '#FFFFFF', sku: 'MCS-WHT-001' },
      { name: 'Slip Black', hex: '#000000', sku: 'MCS-BLK-001' },
      { name: 'Minimal Gray', hex: '#A9A9A9', sku: 'MCS-GRY-001' },
      { name: 'Chic Navy', hex: '#000080', sku: 'MCS-NVY-001' },
    ],
    material: 'Canvas/knit upper, Elastic sides, Rubber sole',
    details: ['Type: Slip-on', 'Convenience: Maximum', 'Style: Minimal'],
    features: ['Easy slip-on', 'Minimalist design', 'All-day comfort', 'Casual ready'],
    stock: 142,
    stockStatus: 'in-stock',
    discount: 54,
    badge: 'sale',
    rating: 4.5,
    reviewCount: 1567,
    slug: 'minimalchic-slip-on-sneaker',
    aliexpressUrl: 'https://aliexpress.com/item/[ADD-YOUR-LINK]',
  },
  {
    id: 'shoe-casual-005',
    name: 'HighSoul Platform Sneaker',
    category: 'shoes',
    subcategory: 'casual',
    price: 48.99,
    originalPrice: 109.99,
    description: 'Trendy platform sneaker with height and style',
    longDescription: 'HighSoul combines platform sole technology with contemporary design. Perfect for fashion-forward casual looks with added height and distinctive style.',
    images: ['https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=800&h=800&fit=crop'],
    thumbnail: 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=200&h=200&fit=crop',
    gender: 'women',
    sizes: ['34', '35', '36', '37', '38', '39', '40', '41', '42', '43'],
    colors: [
      { name: 'Platform White', hex: '#FFFFFF', sku: 'HPS-WHT-001' },
      { name: 'Platform Black', hex: '#000000', sku: 'HPS-BLK-001' },
      { name: 'Platform Pink', hex: '#FFB6C1', sku: 'HPS-PNK-001' },
      { name: 'Platform Gray', hex: '#C0C0C0', sku: 'HPS-GRY-001' },
    ],
    material: 'Thick canvas, Platform sole, Cushioned insole',
    details: ['Height added: 3-4cm', 'Style: Trendy', 'Comfort: Cushioned'],
    features: ['Platform sole', 'Height enhancement', 'Trendy design', 'Cushioned comfort'],
    stock: 68,
    stockStatus: 'in-stock',
    discount: 56,
    badge: 'new',
    rating: 4.6,
    reviewCount: 1234,
    slug: 'highsoul-platform-sneaker',
    aliexpressUrl: 'https://aliexpress.com/item/[ADD-YOUR-LINK]',
  },
  {
    id: 'shoe-casual-006',
    name: 'SportLux Hybrid Casual Sneaker',
    category: 'shoes',
    subcategory: 'casual',
    price: 46.99,
    originalPrice: 104.99,
    description: 'Hybrid sneaker combining sports and casual aesthetics',
    longDescription: 'SportLux bridges the gap between athletic and casual. Combines performance design elements with everyday casual styling for versatile wear.',
    images: ['https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=800&h=800&fit=crop'],
    thumbnail: 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46'],
    colors: [
      { name: 'Hybrid White', hex: '#FFFFFF', sku: 'SLH-WHT-001' },
      { name: 'Hybrid Black', hex: '#000000', sku: 'SLH-BLK-001' },
      { name: 'Sport Gray', hex: '#808080', sku: 'SLH-GRY-001' },
      { name: 'Tech Blue', hex: '#0099FF', sku: 'SLH-BLU-001' },
    ],
    material: 'Mixed mesh/leather, Responsive foam, Sporty outsole',
    details: ['Type: Hybrid', 'Performance: Sport', 'Style: Casual'],
    features: ['Hybrid design', 'Sport-casual blend', 'Versatile wear', 'Modern aesthetics'],
    stock: 105,
    stockStatus: 'in-stock',
    discount: 55,
    badge: 'bestseller',
    rating: 4.7,
    reviewCount: 1945,
    slug: 'sportlux-hybrid-casual-sneaker',
    aliexpressUrl: 'https://aliexpress.com/item/[ADD-YOUR-LINK]',
  },
  {
    id: 'shoe-casual-007',
    name: 'VintagePulse Retro Casual Shoe',
    category: 'shoes',
    subcategory: 'casual',
    price: 41.99,
    originalPrice: 89.99,
    description: 'Vintage-inspired casual shoe with contemporary comfort',
    longDescription: 'VintagePulse captures retro aesthetics with modern comfort technology. Perfect for vintage fashion enthusiasts and classic style lovers.',
    images: ['https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=800&h=800&fit=crop'],
    thumbnail: 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46'],
    colors: [
      { name: 'Vintage Cream', hex: '#FFFDD0', sku: 'VPC-CRM-001' },
      { name: 'Vintage Brown', hex: '#8B6914', sku: 'VPC-BRN-001' },
      { name: 'Vintage Navy', hex: '#003d5c', sku: 'VPC-NVY-001' },
      { name: 'Vintage Gray', hex: '#969696', sku: 'VPC-GRY-001' },
    ],
    material: 'Suede, Soft lining, Vintage-style sole',
    details: ['Era: Vintage-inspired', 'Material: Suede', 'Comfort: Modern'],
    features: ['Vintage design', 'Modern comfort', 'Classic appeal', 'Suede construction'],
    stock: 87,
    stockStatus: 'in-stock',
    discount: 53,
    badge: 'sale',
    rating: 4.5,
    reviewCount: 1423,
    slug: 'vintagepulse-retro-casual-shoe',
    aliexpressUrl: 'https://aliexpress.com/item/[ADD-YOUR-LINK]',
  },
  {
    id: 'shoe-casual-008',
    name: 'EverydayMuse Comfort Casual Sneaker',
    category: 'shoes',
    subcategory: 'casual',
    price: 39.99,
    originalPrice: 84.99,
    description: 'Ultimate comfort casual sneaker for everyday wear',
    longDescription: 'EverydayMuse prioritizes comfort for all-day wear. Soft cushioning, breathable materials, and design that works for any casual occasion.',
    images: ['https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=800&h=800&fit=crop'],
    thumbnail: 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=200&h=200&fit=crop',
    gender: 'women',
    sizes: ['34', '35', '36', '37', '38', '39', '40', '41', '42', '43'],
    colors: [
      { name: 'Comfort White', hex: '#FFFFFF', sku: 'EMC-WHT-001' },
      { name: 'Comfort Black', hex: '#000000', sku: 'EMC-BLK-001' },
      { name: 'Comfort Pink', hex: '#FFB6C1', sku: 'EMC-PNK-001' },
      { name: 'Comfort Beige', hex: '#F5F5DC', sku: 'EMC-BGE-001' },
    ],
    material: 'Soft mesh, Memory foam insole, Cushioned sole',
    details: ['Comfort: Maximum', 'Material: Soft', 'All-day ready: Yes'],
    features: ['Maximum comfort', 'Soft materials', 'Memory foam', 'All-day wear'],
    stock: 156,
    stockStatus: 'in-stock',
    discount: 53,
    badge: 'bestseller',
    rating: 4.8,
    reviewCount: 2567,
    slug: 'everydaymuse-comfort-casual-sneaker',
    aliexpressUrl: 'https://aliexpress.com/item/[ADD-YOUR-LINK]',
  },

  // ========== T-SHIRTS (7 products) ==========
  {
    id: 'clothing-tee-001',
    name: 'Essential Crew Neck T-Shirt',
    category: 'clothing',
    subcategory: 'tshirt',
    price: 12.99,
    originalPrice: 29.99,
    description: 'Classic essential crew neck t-shirt in premium cotton',
    longDescription: 'The foundation of any wardrobe. Premium cotton construction, perfect fit, and timeless design. Available in all classic colors for versatile styling.',
    images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&h=800&fit=crop'],
    thumbnail: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Pure White', hex: '#FFFFFF', sku: 'ECN-WHT-001' },
      { name: 'Classic Black', hex: '#000000', sku: 'ECN-BLK-001' },
      { name: 'Navy', hex: '#001f3f', sku: 'ECN-NVY-001' },
      { name: 'Gray', hex: '#808080', sku: 'ECN-GRY-001' },
      { name: 'Red', hex: '#FF0000', sku: 'ECN-RED-001' },
      { name: 'Heather Gray', hex: '#A9A9A9', sku: 'ECN-HGR-001' },
    ],
    material: '100% Premium cotton',
    details: ['Fit: Regular', 'Weight: 180gsm', 'Neck: Crew'],
    features: ['Premium cotton', 'Perfect fit', 'Timeless design', 'Versatile colors'],
    stock: 350,
    stockStatus: 'in-stock',
    discount: 57,
    badge: 'bestseller',
    rating: 4.8,
    reviewCount: 4523,
    slug: 'essential-crew-neck-tshirt',
    aliexpressUrl: 'https://aliexpress.com/item/[ADD-YOUR-LINK]',
  },
  {
    id: 'clothing-tee-002',
    name: 'Performance Moisture-Wicking T-Shirt',
    category: 'clothing',
    subcategory: 'tshirt',
    price: 16.99,
    originalPrice: 39.99,
    description: 'Advanced moisture-wicking tee for athletic performance',
    longDescription: 'Engineered for athletes. Advanced moisture-wicking technology keeps you dry and comfortable during intense workouts and training sessions.',
    images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&h=800&fit=crop'],
    thumbnail: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Tech Black', hex: '#1A1A1A', sku: 'PMW-BLK-001' },
      { name: 'Tech White', hex: '#FFFFFF', sku: 'PMW-WHT-001' },
      { name: 'Sport Gray', hex: '#808080', sku: 'PMW-GRY-001' },
      { name: 'Athletic Blue', hex: '#0066FF', sku: 'PMW-BLU-001' },
    ],
    material: 'Polyester moisture-wicking blend',
    details: ['Technology: Moisture-wicking', 'Fit: Athletic', 'Weight: 160gsm'],
    features: ['Moisture-wicking', 'Athletic fit', 'Breathable', 'Performance-ready'],
    stock: 245,
    stockStatus: 'in-stock',
    discount: 58,
    badge: 'bestseller',
    rating: 4.7,
    reviewCount: 2134,
    slug: 'performance-moisture-wicking-tshirt',
    aliexpressUrl: 'https://aliexpress.com/item/[ADD-YOUR-LINK]',
  },
  {
    id: 'clothing-tee-003',
    name: 'Oversized Streetwear T-Shirt',
    category: 'clothing',
    subcategory: 'tshirt',
    price: 18.99,
    originalPrice: 44.99,
    description: 'Trendy oversized t-shirt for street style fashion',
    longDescription: 'Make a statement with oversized fit. Contemporary streetwear design with premium quality and comfortable oversized silhouette for urban style.',
    images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&h=800&fit=crop'],
    thumbnail: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Oversized Black', hex: '#000000', sku: 'OST-BLK-001' },
      { name: 'Oversized White', hex: '#FFFFFF', sku: 'OST-WHT-001' },
      { name: 'Streetwear Gray', hex: '#696969', sku: 'OST-GRY-001' },
      { name: 'Urban Navy', hex: '#191970', sku: 'OST-NVY-001' },
      { name: 'Hype Purple', hex: '#663399', sku: 'OST-PUR-001' },
    ],
    material: '100% Cotton, heavyweight',
    details: ['Fit: Oversized', 'Weight: 220gsm', 'Style: Streetwear'],
    features: ['Oversized fit', 'Streetwear style', 'Premium quality', 'Modern design'],
    stock: 198,
    stockStatus: 'in-stock',
    discount: 58,
    badge: 'new',
    rating: 4.6,
    reviewCount: 1876,
    slug: 'oversized-streetwear-tshirt',
    aliexpressUrl: 'https://aliexpress.com/item/[ADD-YOUR-LINK]',
  },
  {
    id: 'clothing-tee-004',
    name: 'V-Neck Premium T-Shirt',
    category: 'clothing',
    subcategory: 'tshirt',
    price: 14.99,
    originalPrice: 34.99,
    description: 'Classic v-neck t-shirt for elevated casual look',
    longDescription: 'Sophisticated v-neck design for a refined casual look. Premium materials and flattering fit make this a wardrobe staple.',
    images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&h=800&fit=crop'],
    thumbnail: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=200&h=200&fit=crop',
    gender: 'women',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Elegant White', hex: '#FFFFFF', sku: 'VNP-WHT-001' },
      { name: 'Sophisticated Black', hex: '#000000', sku: 'VNP-BLK-001' },
      { name: 'Refined Gray', hex: '#A9A9A9', sku: 'VNP-GRY-001' },
      { name: 'Elegant Navy', hex: '#001f3f', sku: 'VNP-NVY-001' },
      { name: 'Rose Pink', hex: '#FF69B4', sku: 'VNP-RSE-001' },
    ],
    material: '95% Cotton, 5% Elastane',
    details: ['Fit: Fitted', 'Neck: V-neck', 'Weight: 170gsm'],
    features: ['V-neck design', 'Flattering fit', 'Premium material', 'Refined style'],
    stock: 212,
    stockStatus: 'in-stock',
    discount: 57,
    badge: 'bestseller',
    rating: 4.8,
    reviewCount: 2345,
    slug: 'vneck-premium-tshirt',
    aliexpressUrl: 'https://aliexpress.com/item/[ADD-YOUR-LINK]',
  },
  {
    id: 'clothing-tee-005',
    name: 'Graphic Statement T-Shirt',
    category: 'clothing',
    subcategory: 'tshirt',
    price: 19.99,
    originalPrice: 49.99,
    description: 'Bold graphic tee for expressive personal style',
    longDescription: 'Make a statement with our graphic t-shirt collection. High-quality prints, comfortable fit, and designs that let your personality shine.',
    images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&h=800&fit=crop'],
    thumbnail: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Black Base', hex: '#000000', sku: 'GST-BLK-001' },
      { name: 'White Base', hex: '#FFFFFF', sku: 'GST-WHT-001' },
      { name: 'Navy Base', hex: '#001f3f', sku: 'GST-NVY-001' },
      { name: 'Gray Base', hex: '#808080', sku: 'GST-GRY-001' },
    ],
    material: '100% Cotton',
    details: ['Print: High-quality', 'Design: Graphic', 'Weight: 185gsm'],
    features: ['Bold graphics', 'Quality prints', 'Expressive style', 'Comfortable wear'],
    stock: 167,
    stockStatus: 'in-stock',
    discount: 60,
    badge: 'sale',
    rating: 4.5,
    reviewCount: 1567,
    slug: 'graphic-statement-tshirt',
    aliexpressUrl: 'https://aliexpress.com/item/[ADD-YOUR-LINK]',
  },
  {
    id: 'clothing-tee-006',
    name: 'Slim-Fit Athletic T-Shirt',
    category: 'clothing',
    subcategory: 'tshirt',
    price: 15.99,
    originalPrice: 37.99,
    description: 'Slim-fit t-shirt for athletic silhouette',
    longDescription: 'Tailored slim-fit design flatters athletic builds. Premium cotton blend provides comfort and durability for daily wear and workouts.',
    images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&h=800&fit=crop'],
    thumbnail: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=200&h=200&fit=crop',
    gender: 'men',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Sharp Black', hex: '#000000', sku: 'SFA-BLK-001' },
      { name: 'Sharp White', hex: '#FFFFFF', sku: 'SFA-WHT-001' },
      { name: 'Fitted Gray', hex: '#808080', sku: 'SFA-GRY-001' },
      { name: 'Athletic Blue', hex: '#0066FF', sku: 'SFA-BLU-001' },
      { name: 'Bold Red', hex: '#FF0000', sku: 'SFA-RED-001' },
    ],
    material: '95% Cotton, 5% Elastane',
    details: ['Fit: Slim', 'Stretch: Yes', 'Weight: 180gsm'],
    features: ['Slim-fit design', 'Athletic flattering', 'Stretch material', 'All-day comfort'],
    stock: 234,
    stockStatus: 'in-stock',
    discount: 58,
    badge: 'bestseller',
    rating: 4.7,
    reviewCount: 1923,
    slug: 'slim-fit-athletic-tshirt',
    aliexpressUrl: 'https://aliexpress.com/item/[ADD-YOUR-LINK]',
  },
  {
    id: 'clothing-tee-007',
    name: 'Henley Casual T-Shirt',
    category: 'clothing',
    subcategory: 'tshirt',
    price: 17.99,
    originalPrice: 42.99,
    description: 'Classic henley design for smart-casual style',
    longDescription: 'Timeless henley with button-up detail. Perfect for layering or wearing alone for a sophisticated casual look. Premium construction for durability.',
    images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&h=800&fit=crop'],
    thumbnail: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=200&h=200&fit=crop',
    gender: 'men',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Classic White', hex: '#FFFFFF', sku: 'HEN-WHT-001' },
      { name: 'Classic Black', hex: '#000000', sku: 'HEN-BLK-001' },
      { name: 'Navy Henley', hex: '#001f3f', sku: 'HEN-NVY-001' },
      { name: 'Heather Gray', hex: '#A9A9A9', sku: 'HEN-HGR-001' },
      { name: 'Burgundy', hex: '#800000', sku: 'HEN-BUR-001' },
    ],
    material: '100% Premium cotton',
    details: ['Collar: Henley', 'Buttons: Yes', 'Weight: 190gsm'],
    features: ['Henley design', 'Button detail', 'Smart-casual ready', 'Layering friendly'],
    stock: 189,
    stockStatus: 'in-stock',
    discount: 58,
    badge: 'new',
    rating: 4.6,
    reviewCount: 1634,
    slug: 'henley-casual-tshirt',
    aliexpressUrl: 'https://aliexpress.com/item/[ADD-YOUR-LINK]',
  },

  // ========== HOODIES & SWEATS (7 products) ==========
  {
    id: 'clothing-hood-001',
    name: 'Classic Pullover Hoodie',
    category: 'clothing',
    subcategory: 'hoodie',
    price: 34.99,
    originalPrice: 79.99,
    description: 'Timeless pullover hoodie for comfort and warmth',
    longDescription: 'The essential hoodie. Soft cotton blend, kangaroo pocket, and comfortable fit make this perfect for layering or casual wear. Available in all classic colors.',
    images: ['https://images.unsplash.com/photo-1556821552-7f41c5d440db?w=800&h=800&fit=crop'],
    thumbnail: 'https://images.unsplash.com/photo-1556821552-7f41c5d440db?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Classic Black', hex: '#000000', sku: 'CPH-BLK-001' },
      { name: 'Classic Gray', hex: '#808080', sku: 'CPH-GRY-001' },
      { name: 'Navy Blue', hex: '#001f3f', sku: 'CPH-NVY-001' },
      { name: 'Forest Green', hex: '#228B22', sku: 'CPH-GRN-001' },
      { name: 'Burgundy', hex: '#800000', sku: 'CPH-BUR-001' },
    ],
    material: '80% Cotton, 20% Polyester blend',
    details: ['Style: Pullover', 'Pocket: Kangaroo', 'Weight: 280gsm'],
    features: ['Comfortable fit', 'Kangaroo pocket', 'Premium blend', 'Warm and cozy'],
    stock: 276,
    stockStatus: 'in-stock',
    discount: 56,
    badge: 'bestseller',
    rating: 4.8,
    reviewCount: 3456,
    slug: 'classic-pullover-hoodie',
    aliexpressUrl: 'https://aliexpress.com/item/[ADD-YOUR-LINK]',
  },
  {
    id: 'clothing-hood-002',
    name: 'Premium Zip-Up Hoodie',
    category: 'clothing',
    subcategory: 'hoodie',
    price: 39.99,
    originalPrice: 94.99,
    description: 'Premium zip-up hoodie for easy layering and style',
    longDescription: 'Upgrade your hoodie game with our premium zip-up design. High-quality materials, tapered fit, and stylish details for a sophisticated casual look.',
    images: ['https://images.unsplash.com/photo-1556821552-7f41c5d440db?w=800&h=800&fit=crop'],
    thumbnail: 'https://images.unsplash.com/photo-1556821552-7f41c5d440db?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Premium Black', hex: '#1A1A1A', sku: 'PZH-BLK-001' },
      { name: 'Premium Gray', hex: '#A9A9A9', sku: 'PZH-GRY-001' },
      { name: 'Urban Navy', hex: '#191970', sku: 'PZH-NVY-001' },
      { name: 'Modern White', hex: '#F5F5F5', sku: 'PZH-WHT-001' },
      { name: 'Charcoal', hex: '#36454F', sku: 'PZH-CHL-001' },
    ],
    material: '85% Cotton, 15% Polyester premium blend',
    details: ['Style: Zip-up', 'Fit: Tapered', 'Weight: 300gsm'],
    features: ['Zip-up design', 'Premium quality', 'Tapered fit', 'Easy layering'],
    stock: 198,
    stockStatus: 'in-stock',
    discount: 58,
    badge: 'bestseller',
    rating: 4.8,
    reviewCount: 2134,
    slug: 'premium-zipup-hoodie',
    aliexpressUrl: 'https://aliexpress.com/item/[ADD-YOUR-LINK]',
  },
  {
    id: 'clothing-hood-003',
    name: 'Athletic Performance Hoodie',
    category: 'clothing',
    subcategory: 'hoodie',
    price: 42.99,
    originalPrice: 99.99,
    description: 'High-performance hoodie for athletes and training',
    longDescription: 'Engineered for active wear. Moisture-wicking technology, ergonomic design, and premium materials make this perfect for training and active lifestyle.',
    images: ['https://images.unsplash.com/photo-1556821552-7f41c5d440db?w=800&h=800&fit=crop'],
    thumbnail: 'https://images.unsplash.com/photo-1556821552-7f41c5d440db?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Tech Black', hex: '#000000', sku: 'APH-BLK-001' },
      { name: 'Tech Gray', hex: '#696969', sku: 'APH-GRY-001' },
      { name: 'Athletic Navy', hex: '#0066FF', sku: 'APH-NVY-001' },
      { name: 'Performance Blue', hex: '#4169E1', sku: 'APH-BLU-001' },
    ],
    material: 'Polyester moisture-wicking blend',
    details: ['Technology: Moisture-wicking', 'Fit: Athletic', 'Weight: 270gsm'],
    features: ['Moisture-wicking', 'Athletic fit', 'Performance ready', 'Breathable'],
    stock: 145,
    stockStatus: 'in-stock',
    discount: 57,
    badge: 'new',
    rating: 4.7,
    reviewCount: 1645,
    slug: 'athletic-performance-hoodie',
    aliexpressUrl: 'https://aliexpress.com/item/[ADD-YOUR-LINK]',
  },
  {
    id: 'clothing-hood-004',
    name: 'Oversized Comfort Hoodie',
    category: 'clothing',
    subcategory: 'hoodie',
    price: 36.99,
    originalPrice: 84.99,
    description: 'Extra comfortable oversized hoodie for relaxation',
    longDescription: 'Ultimate comfort hoodie with oversized silhouette. Perfect for lounging, studying, or cozy everyday wear. Soft, warm, and incredibly comfortable.',
    images: ['https://images.unsplash.com/photo-1556821552-7f41c5d440db?w=800&h=800&fit=crop'],
    thumbnail: 'https://images.unsplash.com/photo-1556821552-7f41c5d440db?w=200&h=200&fit=crop',
    gender: 'women',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Cozy Black', hex: '#000000', sku: 'OCH-BLK-001' },
      { name: 'Cozy Gray', hex: '#A9A9A9', sku: 'OCH-GRY-001' },
      { name: 'Cozy Pink', hex: '#FFB6C1', sku: 'OCH-PNK-001' },
      { name: 'Cozy Cream', hex: '#FFFDD0', sku: 'OCH-CRM-001' },
    ],
    material: '100% Soft cotton blend',
    details: ['Fit: Oversized', 'Comfort: Maximum', 'Weight: 320gsm'],
    features: ['Oversized fit', 'Maximum comfort', 'Soft materials', 'Perfect for lounging'],
    stock: 212,
    stockStatus: 'in-stock',
    discount: 57,
    badge: 'bestseller',
    rating: 4.9,
    reviewCount: 2789,
    slug: 'oversized-comfort-hoodie',
    aliexpressUrl: 'https://aliexpress.com/item/[ADD-YOUR-LINK]',
  },
  {
    id: 'clothing-hood-005',
    name: 'Streetwear Graphics Hoodie',
    category: 'clothing',
    subcategory: 'hoodie',
    price: 41.99,
    originalPrice: 99.99,
    description: 'Statement hoodie with bold graphics for street style',
    longDescription: 'Express your style with bold graphics. Premium quality prints, comfortable fit, and streetwear aesthetic make this a statement piece.',
    images: ['https://images.unsplash.com/photo-1556821552-7f41c5d440db?w=800&h=800&fit=crop'],
    thumbnail: 'https://images.unsplash.com/photo-1556821552-7f41c5d440db?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Hype Black', hex: '#000000', sku: 'SGH-BLK-001' },
      { name: 'Hype White', hex: '#FFFFFF', sku: 'SGH-WHT-001' },
      { name: 'Urban Navy', hex: '#001f3f', sku: 'SGH-NVY-001' },
      { name: 'Streetwear Gray', hex: '#696969', sku: 'SGH-GRY-001' },
    ],
    material: '80% Cotton, 20% Polyester',
    details: ['Graphics: Bold print', 'Style: Streetwear', 'Weight: 290gsm'],
    features: ['Bold graphics', 'Streetwear style', 'Premium prints', 'Statement piece'],
    stock: 156,
    stockStatus: 'in-stock',
    discount: 58,
    badge: 'sale',
    rating: 4.6,
    reviewCount: 1534,
    slug: 'streetwear-graphics-hoodie',
    aliexpressUrl: 'https://aliexpress.com/item/[ADD-YOUR-LINK]',
  },
  {
    id: 'clothing-hood-006',
    name: 'Minimal Monochrome Hoodie',
    category: 'clothing',
    subcategory: 'hoodie',
    price: 37.99,
    originalPrice: 89.99,
    description: 'Minimalist hoodie with clean monochrome design',
    longDescription: 'Sophisticated minimalism. Clean lines, neutral colors, and premium quality define this essential hoodie. Perfect for any wardrobe.',
    images: ['https://images.unsplash.com/photo-1556821552-7f41c5d440db?w=800&h=800&fit=crop'],
    thumbnail: 'https://images.unsplash.com/photo-1556821552-7f41c5d440db?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Pure Black', hex: '#000000', sku: 'MMH-BLK-001' },
      { name: 'Pure White', hex: '#FFFFFF', sku: 'MMH-WHT-001' },
      { name: 'Stone Gray', hex: '#808080', sku: 'MMH-GRY-001' },
      { name: 'Charcoal', hex: '#36454F', sku: 'MMH-CHR-001' },
    ],
    material: '90% Cotton, 10% Polyester',
    details: ['Design: Minimal', 'Colors: Monochrome', 'Weight: 280gsm'],
    features: ['Minimalist design', 'Clean lines', 'Monochrome colors', 'Versatile wear'],
    stock: 189,
    stockStatus: 'in-stock',
    discount: 58,
    badge: 'new',
    rating: 4.7,
    reviewCount: 1423,
    slug: 'minimal-monochrome-hoodie',
    aliexpressUrl: 'https://aliexpress.com/item/[ADD-YOUR-LINK]',
  },
  {
    id: 'clothing-hood-007',
    name: 'Premium Fleece Hoodie',
    category: 'clothing',
    subcategory: 'hoodie',
    price: 43.99,
    originalPrice: 104.99,
    description: 'Ultra-soft fleece hoodie for maximum warmth and comfort',
    longDescription: 'Luxurious fleece construction for ultimate warmth and softness. Premium materials, meticulous construction, and superior comfort make this a winter essential.',
    images: ['https://images.unsplash.com/photo-1556821552-7f41c5d440db?w=800&h=800&fit=crop'],
    thumbnail: 'https://images.unsplash.com/photo-1556821552-7f41c5d440db?w=200&h=200&fit=crop',
    gender: 'women',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Luxe Black', hex: '#000000', sku: 'PFH-BLK-001' },
      { name: 'Luxe Gray', hex: '#A9A9A9', sku: 'PFH-GRY-001' },
      { name: 'Cozy Cream', hex: '#FFFDD0', sku: 'PFH-CRM-001' },
      { name: 'Soft Pink', hex: '#FFB6C1', sku: 'PFH-PNK-001' },
    ],
    material: '100% Premium fleece',
    details: ['Material: Premium fleece', 'Warmth: Maximum', 'Weight: 350gsm'],
    features: ['Premium fleece', 'Ultra soft', 'Maximum warmth', 'Luxury feel'],
    stock: 124,
    stockStatus: 'in-stock',
    discount: 58,
    badge: 'bestseller',
    rating: 4.9,
    reviewCount: 2156,
    slug: 'premium-fleece-hoodie',
    aliexpressUrl: 'https://aliexpress.com/item/[ADD-YOUR-LINK]',
  },

  // ========== ACCESSORIES (6 products) ==========
  {
    id: 'access-sock-001',
    name: 'Performance Sport Socks (Pack of 3)',
    category: 'accessories',
    subcategory: 'socks',
    price: 8.99,
    originalPrice: 19.99,
    description: 'High-performance sport socks for running and training',
    longDescription: 'Engineered for performance. Moisture-wicking, arch support, and cushioning make these perfect for any athletic activity.',
    images: ['https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=800&h=800&fit=crop'],
    thumbnail: 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['One Size'],
    colors: [
      { name: 'Black', hex: '#000000', sku: 'PSS-BLK-001' },
      { name: 'White', hex: '#FFFFFF', sku: 'PSS-WHT-001' },
      { name: 'Gray', hex: '#808080', sku: 'PSS-GRY-001' },
      { name: 'Navy', hex: '#001f3f', sku: 'PSS-NVY-001' },
    ],
    material: '75% Cotton, 20% Polyester, 5% Elastane',
    details: ['Pack: 3 pairs', 'Technology: Moisture-wicking', 'Support: Arch support'],
    features: ['Moisture-wicking', 'Arch support', 'Cushioning', 'Performance ready'],
    stock: 450,
    stockStatus: 'in-stock',
    discount: 55,
    badge: 'bestseller',
    rating: 4.6,
    reviewCount: 2134,
    slug: 'performance-sport-socks-pack-of-3',
    aliexpressUrl: 'https://aliexpress.com/item/[ADD-YOUR-LINK]',
  },
  {
    id: 'access-cap-001',
    name: 'Classic Adjustable Baseball Cap',
    category: 'accessories',
    subcategory: 'hat',
    price: 12.99,
    originalPrice: 29.99,
    description: 'Timeless baseball cap for casual and sports wear',
    longDescription: 'The essential cap. Adjustable fit, classic design, and quality construction make this perfect for any outfit. Available in multiple colors.',
    images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&h=800&fit=crop'],
    thumbnail: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['One Size (Adjustable)'],
    colors: [
      { name: 'Classic Black', hex: '#000000', sku: 'CAP-BLK-001' },
      { name: 'Classic White', hex: '#FFFFFF', sku: 'CAP-WHT-001' },
      { name: 'Navy', hex: '#001f3f', sku: 'CAP-NVY-001' },
      { name: 'Red', hex: '#FF0000', sku: 'CAP-RED-001' },
      { name: 'Khaki', hex: '#F0E68C', sku: 'CAP-KHK-001' },
      { name: 'Gray', hex: '#808080', sku: 'CAP-GRY-001' },
    ],
    material: 'Cotton twill',
    details: ['Type: Baseball cap', 'Fit: Adjustable', 'Closure: Velcro'],
    features: ['Classic design', 'Adjustable fit', 'Quality construction', 'Versatile colors'],
    stock: 325,
    stockStatus: 'in-stock',
    discount: 57,
    badge: 'bestseller',
    rating: 4.7,
    reviewCount: 1923,
    slug: 'classic-adjustable-baseball-cap',
    aliexpressUrl: 'https://aliexpress.com/item/[ADD-YOUR-LINK]',
  },
  {
    id: 'access-bag-001',
    name: 'Sport Gym Backpack',
    category: 'accessories',
    subcategory: 'bag',
    price: 24.99,
    originalPrice: 59.99,
    description: 'Spacious gym backpack for training and daily use',
    longDescription: 'Designed for athletes. Multiple compartments, padded laptop sleeve, and ergonomic design make this perfect for gym, work, or travel.',
    images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&h=800&fit=crop'],
    thumbnail: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['One Size'],
    colors: [
      { name: 'Gym Black', hex: '#000000', sku: 'SGB-BLK-001' },
      { name: 'Sport Gray', hex: '#808080', sku: 'SGB-GRY-001' },
      { name: 'Team Navy', hex: '#001f3f', sku: 'SGB-NVY-001' },
    ],
    material: 'Polyester, nylon reinforcement',
    details: ['Capacity: 30-40L', 'Compartments: Multiple', 'Padding: Yes'],
    features: ['Multiple compartments', 'Padded laptop sleeve', 'Ergonomic design', 'Durable material'],
    stock: 156,
    stockStatus: 'in-stock',
    discount: 58,
    badge: 'bestseller',
    rating: 4.7,
    reviewCount: 1534,
    slug: 'sport-gym-backpack',
    aliexpressUrl: 'https://aliexpress.com/item/[ADD-YOUR-LINK]',
  },
  {
    id: 'access-wrist-001',
    name: 'Sports Fitness Tracker Watch',
    category: 'accessories',
    subcategory: 'wearable',
    price: 34.99,
    originalPrice: 89.99,
    description: 'Advanced fitness tracker watch for sports and health monitoring',
    longDescription: 'Monitor your fitness with style. Heart rate tracking, step counter, sleep monitoring, and multiple sports modes make this essential for active lifestyles.',
    images: ['https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&h=800&fit=crop'],
    thumbnail: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['One Size (Adjustable)'],
    colors: [
      { name: 'Black', hex: '#000000', sku: 'SFT-BLK-001' },
      { name: 'Silver', hex: '#C0C0C0', sku: 'SFT-SLV-001' },
      { name: 'Blue', hex: '#0099FF', sku: 'SFT-BLU-001' },
    ],
    material: 'Silicone strap, Plastic/metal case',
    details: ['Functions: Heart rate, steps, sleep', 'Battery: 10+ days', 'Water resistant: Yes'],
    features: ['Heart rate tracking', 'Step counter', 'Sleep monitoring', 'Multiple sport modes'],
    stock: 98,
    stockStatus: 'in-stock',
    discount: 61,
    badge: 'new',
    rating: 4.6,
    reviewCount: 1245,
    slug: 'sports-fitness-tracker-watch',
    aliexpressUrl: 'https://aliexpress.com/item/[ADD-YOUR-LINK]',
  },
  {
    id: 'access-band-001',
    name: 'Resistance Loop Band Set (Set of 4)',
    category: 'accessories',
    subcategory: 'equipment',
    price: 9.99,
    originalPrice: 24.99,
    description: 'Versatile resistance loop band set for training',
    longDescription: 'Perfect for strength training, physical therapy, and pilates. Multiple resistance levels allow progressive training for all fitness levels.',
    images: ['https://images.unsplash.com/photo-1533899298318-6b8da08a523e?w=800&h=800&fit=crop'],
    thumbnail: 'https://images.unsplash.com/photo-1533899298318-6b8da08a523e?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['One Size'],
    colors: [
      { name: 'Multi-color Set', hex: '#FFFFFF', sku: 'RLB-SET-001' },
    ],
    material: 'Natural rubber latex',
    details: ['Set: 4 levels', 'Resistance: Light to heavy', 'Material: Latex'],
    features: ['Multiple resistance levels', 'Versatile training', 'Portable', 'Durable'],
    stock: 234,
    stockStatus: 'in-stock',
    discount: 60,
    badge: 'bestseller',
    rating: 4.5,
    reviewCount: 987,
    slug: 'resistance-loop-band-set-of-4',
    aliexpressUrl: 'https://aliexpress.com/item/[ADD-YOUR-LINK]',
  },
  {
    id: 'access-bottle-001',
    name: 'Stainless Steel Water Bottle (750ml)',
    category: 'accessories',
    subcategory: 'water-bottle',
    price: 13.99,
    originalPrice: 34.99,
    description: 'Durable stainless steel water bottle for hydration',
    longDescription: 'Stay hydrated in style. Double-wall insulated, keeps drinks cold for 24 hours or hot for 12 hours. Perfect for gym, office, or outdoor activities.',
    images: ['https://images.unsplash.com/photo-1599599810694-6c1aa1cbc5a7?w=800&h=800&fit=crop'],
    thumbnail: 'https://images.unsplash.com/photo-1599599810694-6c1aa1cbc5a7?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['750ml'],
    colors: [
      { name: 'Stainless Steel', hex: '#C0C0C0', sku: 'SWB-STS-001' },
      { name: 'Black', hex: '#000000', sku: 'SWB-BLK-001' },
      { name: 'Navy Blue', hex: '#001f3f', sku: 'SWB-NVY-001' },
      { name: 'Red', hex: '#FF0000', sku: 'SWB-RED-001' },
    ],
    material: 'Stainless steel, silicone grip',
    details: ['Capacity: 750ml', 'Insulation: Double-wall', 'Keeps cold: 24 hours'],
    features: ['Double-wall insulated', 'Keeps drinks cold/hot', 'Durable', 'Eco-friendly'],
    stock: 287,
    stockStatus: 'in-stock',
    discount: 60,
    badge: 'bestseller',
    rating: 4.8,
    reviewCount: 2345,
    slug: 'stainless-steel-water-bottle-750ml',
    aliexpressUrl: 'https://aliexpress.com/item/[ADD-YOUR-LINK]',
  },

  // ========== EQUIPMENT (3 products) ==========
  {
    id: 'equip-jump-001',
    name: 'Speed Jump Rope (Adjustable)',
    category: 'equipment',
    subcategory: 'jump-rope',
    price: 11.99,
    originalPrice: 29.99,
    description: 'High-speed adjustable jump rope for cardio training',
    longDescription: 'Professional-grade jump rope for cardio, boxing, and agility training. Adjustable length, ball-bearing handles, and speed cable design for optimal performance.',
    images: ['https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&h=800&fit=crop'],
    thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['Adjustable'],
    colors: [
      { name: 'Black/Red', hex: '#000000', sku: 'SJR-BRD-001' },
      { name: 'Blue/White', hex: '#0099FF', sku: 'SJR-BWH-001' },
      { name: 'Black/Gold', hex: '#FFD700', sku: 'SJR-BGR-001' },
    ],
    material: 'Steel cable, Rubber handles, Ball bearings',
    details: ['Type: Speed rope', 'Adjustable: Yes', 'Bearings: Ball bearing'],
    features: ['High-speed design', 'Adjustable length', 'Ball-bearing handles', 'Cardio training'],
    stock: 167,
    stockStatus: 'in-stock',
    discount: 60,
    badge: 'bestseller',
    rating: 4.7,
    reviewCount: 1234,
    slug: 'speed-jump-rope-adjustable',
    aliexpressUrl: 'https://aliexpress.com/item/[ADD-YOUR-LINK]',
  },
  {
    id: 'equip-yoga-001',
    name: 'Premium Yoga Mat (6mm)',
    category: 'equipment',
    subcategory: 'yoga-mat',
    price: 16.99,
    originalPrice: 44.99,
    description: 'Comfortable 6mm yoga mat for all practices',
    longDescription: 'Premium quality yoga mat with excellent grip and cushioning. Non-slip surface, eco-friendly material, and portability make it perfect for home, studio, or travel.',
    images: ['https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&h=800&fit=crop'],
    thumbnail: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['183cm x 61cm x 6mm'],
    colors: [
      { name: 'Yoga Purple', hex: '#9933CC', sku: 'PYM-PUR-001' },
      { name: 'Yoga Blue', hex: '#0099FF', sku: 'PYM-BLU-001' },
      { name: 'Yoga Green', hex: '#00AA00', sku: 'PYM-GRN-001' },
      { name: 'Yoga Black', hex: '#000000', sku: 'PYM-BLK-001' },
    ],
    material: 'NBR foam, non-slip surface',
    details: ['Thickness: 6mm', 'Length: 183cm', 'Width: 61cm'],
    features: ['Non-slip surface', 'Cushioned comfort', 'Eco-friendly', 'Portable'],
    stock: 145,
    stockStatus: 'in-stock',
    discount: 62,
    badge: 'new',
    rating: 4.8,
    reviewCount: 987,
    slug: 'premium-yoga-mat-6mm',
    aliexpressUrl: 'https://aliexpress.com/item/[ADD-YOUR-LINK]',
  },
  {
    id: 'equip-dumbell-001',
    name: 'Adjustable Dumbbell Set (5-25 lbs)',
    category: 'equipment',
    subcategory: 'dumbbells',
    price: 45.99,
    originalPrice: 129.99,
    description: 'Adjustable dumbbell set for home strength training',
    longDescription: 'Space-saving adjustable dumbbell set with 5-25 lbs range. Perfect for home gym, strength training, and progressive workouts.',
    images: ['https://images.unsplash.com/photo-1518611505868-48510c2171d7?w=800&h=800&fit=crop'],
    thumbnail: 'https://images.unsplash.com/photo-1518611505868-48510c2171d7?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['5-25 lbs (2-11kg)'],
    colors: [
      { name: 'Black/Gray', hex: '#000000', sku: 'ADS-BG-001' },
    ],
    material: 'Cast iron, rubber coating',
    details: ['Range: 5-25 lbs', 'Increments: 5 lbs', 'Material: Cast iron'],
    features: ['Adjustable weight', 'Space-saving', 'Home gym ready', 'Strength training'],
    stock: 78,
    stockStatus: 'in-stock',
    discount: 65,
    badge: 'bestseller',
    rating: 4.7,
    reviewCount: 567,
    slug: 'adjustable-dumbbell-set-5-25-lbs',
    aliexpressUrl: 'https://aliexpress.com/item/[ADD-YOUR-LINK]',
  },
];
