export interface Product {
  id: string
  name: string
  category: 'shoes' | 'clothing' | 'accessories' | 'equipment'
  subcategory: string
  price: number
  originalPrice?: number
  description: string
  longDescription: string
  images: string[]
  thumbnail: string
  gender: 'men' | 'women' | 'unisex'

  sizes: string[]
  sizeChart?: string

  colors: { name: string; hex: string; sku: string }[]

  material: string
  details: string[]
  features: string[]

  stock: number
  stockStatus: 'in-stock' | 'low-stock' | 'pre-order' | 'out-of-stock'

  discount?: number
  badge?: 'new' | 'bestseller' | 'sale' | 'limited'

  rating: number
  reviewCount: number

  slug: string
}

export const products: Product[] = [
  // ========== SHOES: RUNNING (10 products) ==========
  {
    id: 'shoe-run-001',
    name: 'Velocity Pro Max',
    category: 'shoes',
    subcategory: 'running',
    price: 189,
    description: 'Ultra-lightweight running shoe with responsive foam cushioning',
    longDescription: 'Experience maximum performance with the Velocity Pro Max. Engineered for speed with responsive Quantum foam, breathable mesh upper, and durable rubber outsole. Perfect for road running and track.',
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1460353581641-a1af1d3ba3c1?w=800&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=200&h=200&fit=crop',
    gender: 'men',
    sizes: ['35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46'],
    colors: [
      { name: 'Black', hex: '#000000', sku: 'VEL-PRO-BLK' },
      { name: 'White', hex: '#FFFFFF', sku: 'VEL-PRO-WHT' },
      { name: 'Navy', hex: '#001f3f', sku: 'VEL-PRO-NVY' },
      { name: 'Red', hex: '#FF4136', sku: 'VEL-PRO-RED' },
    ],
    material: 'Mesh upper, foam midsole, rubber outsole',
    details: ['Weight: 220g', 'Drop: 10mm', 'Cushioning: Quantum Foam'],
    features: ['Breathable mesh', 'Responsive cushioning', 'Durable traction', 'Lightweight design'],
    stock: 45,
    stockStatus: 'in-stock',
    discount: 15,
    badge: 'bestseller',
    rating: 4.8,
    reviewCount: 1203,
    slug: 'velocity-pro-max-men',
  },
  {
    id: 'shoe-run-002',
    name: 'Quantum Flow Runner',
    category: 'shoes',
    subcategory: 'running',
    price: 159,
    description: 'Lightweight and responsive running shoe for everyday training',
    longDescription: 'The Quantum Flow offers the perfect balance of comfort and responsiveness. With advanced cushioning and a secure fit, this shoe excels on both short runs and long distances.',
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=200&h=200&fit=crop',
    gender: 'women',
    sizes: ['34', '35', '36', '37', '38', '39', '40', '41', '42', '43'],
    colors: [
      { name: 'Purple', hex: '#9933CC', sku: 'QF-RUN-PUR' },
      { name: 'Gray', hex: '#999999', sku: 'QF-RUN-GRY' },
      { name: 'Pink', hex: '#FF69B4', sku: 'QF-RUN-PNK' },
      { name: 'Black', hex: '#000000', sku: 'QF-RUN-BLK' },
    ],
    material: 'Engineered mesh, cushioning foam, rubber outsole',
    details: ['Weight: 215g', 'Drop: 8mm', "Women's fit"],
    features: ['Anatomical design', 'Responsive feel', 'Breathable upper', 'Eco-friendly materials'],
    stock: 62,
    stockStatus: 'in-stock',
    badge: 'new',
    rating: 4.7,
    reviewCount: 856,
    slug: 'quantum-flow-runner-women',
  },
  {
    id: 'shoe-run-003',
    name: 'Aeromesh Lite',
    category: 'shoes',
    subcategory: 'running',
    price: 99,
    description: 'Entry-level running shoe with great comfort and value',
    longDescription: 'Perfect for beginners and casual runners. The Aeromesh Lite combines affordability with essential running features like cushioned midsole and breathable mesh.',
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46'],
    colors: [
      { name: 'White', hex: '#FFFFFF', sku: 'AERO-WHT' },
      { name: 'Gray', hex: '#999999', sku: 'AERO-GRY' },
      { name: 'Blue', hex: '#0066CC', sku: 'AERO-BLU' },
    ],
    material: 'Mesh and synthetic, foam midsole',
    details: ['Weight: 240g', 'Drop: 10mm'],
    features: ['Budget-friendly', 'Comfortable fit', 'Durable', 'Good ventilation'],
    stock: 120,
    stockStatus: 'in-stock',
    rating: 4.3,
    reviewCount: 432,
    slug: 'aeromesh-lite-unisex',
  },
  {
    id: 'shoe-run-004',
    name: 'TrailblazerX Outdoor',
    category: 'shoes',
    subcategory: 'running',
    price: 175,
    description: 'Trail running shoe with aggressive tread and ankle support',
    longDescription: 'Conquer any terrain with TrailblazerX. Featuring a reinforced toe cap, enhanced grip pattern, and protective midsole for off-road adventures.',
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['36', '37', '38', '39', '40', '41', '42', '43', '44', '45'],
    colors: [
      { name: 'Olive', hex: '#808000', sku: 'TRAIL-OLV' },
      { name: 'Black', hex: '#000000', sku: 'TRAIL-BLK' },
      { name: 'Brown', hex: '#8B4513', sku: 'TRAIL-BRN' },
    ],
    material: 'Reinforced mesh, protective rubber, sticky outsole',
    details: ['Weight: 260g', 'Drop: 12mm', 'Trail-specific'],
    features: ['Aggressive tread', 'Ankle support', 'Water-resistant', 'Rock plate protection'],
    stock: 38,
    stockStatus: 'in-stock',
    badge: 'sale',
    discount: 20,
    rating: 4.6,
    reviewCount: 567,
    slug: 'trailblazer-x-outdoor',
  },
  {
    id: 'shoe-run-005',
    name: 'Speed Elite Marathon',
    category: 'shoes',
    subcategory: 'running',
    price: 199,
    description: 'Racing shoe designed for marathon performances',
    longDescription: 'Built for speed and endurance. The Speed Elite features carbon fiber shank, ultra-responsive cushioning, and lightweight construction for competitive marathon running.',
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=200&h=200&fit=crop',
    gender: 'men',
    sizes: ['37', '38', '39', '40', '41', '42', '43', '44', '45'],
    colors: [
      { name: 'Black', hex: '#000000', sku: 'SPEED-BLK' },
      { name: 'White/Blue', hex: '#0066CC', sku: 'SPEED-BLU' },
      { name: 'Red/Gold', hex: '#FFD700', sku: 'SPEED-GLD' },
    ],
    material: 'Mesh with carbon fiber reinforcement',
    details: ['Weight: 180g', 'Drop: 10mm', 'Race-focused'],
    features: ['Carbon shank', 'Extremely light', 'Responsive foam', 'Premium feel'],
    stock: 25,
    stockStatus: 'low-stock',
    badge: 'bestseller',
    rating: 4.9,
    reviewCount: 892,
    slug: 'speed-elite-marathon-men',
  },

  // ========== SHOES: BASKETBALL (5 products) ==========
  {
    id: 'shoe-bask-001',
    name: 'Air Legend Pro',
    category: 'shoes',
    subcategory: 'basketball',
    price: 229,
    description: 'High-performance basketball shoe inspired by court legends',
    longDescription: 'The Air Legend Pro channels the essence of basketball greatness. Featuring ankle support, explosive cushioning, and court-ready traction.',
    images: [
      'https://images.unsplash.com/photo-1625238003007-278ef42621c3?w=800&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1625238003007-278ef42621c3?w=200&h=200&fit=crop',
    gender: 'men',
    sizes: ['39', '40', '41', '42', '43', '44', '45', '46'],
    colors: [
      { name: 'Black/Gold', hex: '#FFD700', sku: 'AIR-LEG-BLK' },
      { name: 'White/Blue', hex: '#0066CC', sku: 'AIR-LEG-WHT' },
      { name: 'Red/Black', hex: '#FF0000', sku: 'AIR-LEG-RED' },
    ],
    material: 'Premium leather and mesh, responsive foam',
    details: ['Ankle collar: High', 'Weight: 380g'],
    features: ['Ankle support', 'Explosive cushioning', 'Court traction', 'Premium materials'],
    stock: 52,
    stockStatus: 'in-stock',
    badge: 'bestseller',
    discount: 10,
    rating: 4.9,
    reviewCount: 1456,
    slug: 'air-legend-pro-men',
  },
  {
    id: 'shoe-bask-002',
    name: 'Court King Mid',
    category: 'shoes',
    subcategory: 'basketball',
    price: 179,
    description: 'Mid-cut basketball shoe for all-court play',
    longDescription: 'Court King delivers balanced performance for all positions. Mid-cut design offers stability without sacrificing mobility.',
    images: [
      'https://images.unsplash.com/photo-1625238003007-278ef42621c3?w=800&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1625238003007-278ef42621c3?w=200&h=200&fit=crop',
    gender: 'women',
    sizes: ['35', '36', '37', '38', '39', '40', '41', '42'],
    colors: [
      { name: 'Purple/Gold', hex: '#800080', sku: 'COURT-KG-PUR' },
      { name: 'Black/White', hex: '#FFFFFF', sku: 'COURT-KG-BLK' },
      { name: 'Pink/White', hex: '#FFB6C1', sku: 'COURT-KG-PNK' },
    ],
    material: 'Synthetic leather, cushioned midsole',
    details: ['Ankle collar: Mid', 'Weight: 360g'],
    features: ['Mid-cut support', 'All-court performance', 'Good traction', "Women's-specific fit"],
    stock: 64,
    stockStatus: 'in-stock',
    rating: 4.7,
    reviewCount: 678,
    slug: 'court-king-mid-women',
  },

  // ========== SHOES: CASUAL (3 products) ==========
  {
    id: 'shoe-casual-001',
    name: 'Street Style Flex',
    category: 'shoes',
    subcategory: 'casual',
    price: 129,
    description: 'Casual sneaker for everyday wear',
    longDescription: 'Street Style Flex combines comfort with urban aesthetics. Perfect for casual outings, weekends, and street fashion.',
    images: [
      'https://images.unsplash.com/photo-1460353581641-a1af1d3ba3c1?w=800&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1460353581641-a1af1d3ba3c1?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46'],
    colors: [
      { name: 'White', hex: '#FFFFFF', sku: 'STREET-WHT' },
      { name: 'Black', hex: '#000000', sku: 'STREET-BLK' },
      { name: 'Gray', hex: '#999999', sku: 'STREET-GRY' },
      { name: 'Navy', hex: '#001f3f', sku: 'STREET-NVY' },
    ],
    material: 'Canvas and leather, rubber sole',
    details: ['Casual fit', 'Versatile design'],
    features: ['Comfortable', 'Stylish', 'All-day wear', 'Easy to clean'],
    stock: 156,
    stockStatus: 'in-stock',
    badge: 'bestseller',
    rating: 4.5,
    reviewCount: 2341,
    slug: 'street-style-flex-unisex',
  },

  // ========== CLOTHING: T-SHIRTS (5 products) ==========
  {
    id: 'tee-001',
    name: 'Essential Crew Neck Tee',
    category: 'clothing',
    subcategory: 'tees',
    price: 29,
    description: 'Timeless crew neck t-shirt in premium cotton',
    longDescription: 'The Essential Crew Neck is a wardrobe staple. Made from soft, breathable cotton with a classic fit perfect for any occasion.',
    images: [
      'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'White', hex: '#FFFFFF', sku: 'TEE-ENC-WHT' },
      { name: 'Black', hex: '#000000', sku: 'TEE-ENC-BLK' },
      { name: 'Gray', hex: '#808080', sku: 'TEE-ENC-GRY' },
      { name: 'Navy', hex: '#001f3f', sku: 'TEE-ENC-NVY' },
    ],
    material: '100% cotton',
    details: ['Classic fit', 'Crew neck', 'Comfortable'],
    features: ['Soft cotton', 'Durable', 'Versatile', 'Easy care'],
    stock: 234,
    stockStatus: 'in-stock',
    badge: 'bestseller',
    rating: 4.6,
    reviewCount: 3245,
    slug: 'essential-crew-neck-tee',
  },
  {
    id: 'tee-002',
    name: 'Performance Moisture-Wicking Tee',
    category: 'clothing',
    subcategory: 'tees',
    price: 49,
    description: 'Technical t-shirt for active performance',
    longDescription: 'Engineered for athletes. Performance Moisture-Wicking keeps you dry and comfortable during intense workouts.',
    images: [
      'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=200&h=200&fit=crop',
    gender: 'men',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Black', hex: '#000000', sku: 'TEE-PERF-BLK' },
      { name: 'White', hex: '#FFFFFF', sku: 'TEE-PERF-WHT' },
      { name: 'Blue', hex: '#0066CC', sku: 'TEE-PERF-BLU' },
      { name: 'Red', hex: '#FF0000', sku: 'TEE-PERF-RED' },
    ],
    material: '84% polyester, 16% spandex',
    details: ['Moisture-wicking', 'Lightweight', 'Stretch fabric'],
    features: ['Sweat-repelling', 'Breathable', 'Four-way stretch', 'Anti-odor technology'],
    stock: 167,
    stockStatus: 'in-stock',
    badge: 'new',
    rating: 4.7,
    reviewCount: 1856,
    slug: 'performance-moisture-wicking-tee-men',
  },

  // ========== CLOTHING: HOODIES (3 products) ==========
  {
    id: 'hood-001',
    name: 'Classic Pullover Hoodie',
    category: 'clothing',
    subcategory: 'hoodies',
    price: 79,
    description: 'Cozy pullover hoodie for ultimate comfort',
    longDescription: 'The Classic Pullover is a timeless essential. Soft fleece interior, spacious kangaroo pocket, and adjustable drawstrings.',
    images: [
      'https://images.unsplash.com/photo-1556821552-7f41c5d440db?w=800&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1556821552-7f41c5d440db?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Black', hex: '#000000', sku: 'HOOD-PULL-BLK' },
      { name: 'Gray', hex: '#808080', sku: 'HOOD-PULL-GRY' },
      { name: 'Navy', hex: '#001f3f', sku: 'HOOD-PULL-NVY' },
      { name: 'Charcoal', hex: '#36454F', sku: 'HOOD-PULL-CHR' },
    ],
    material: '80% cotton, 20% polyester fleece',
    details: ['Pullover style', 'Fleece-lined', 'Kangaroo pocket'],
    features: ['Cozy fleece', 'Durable', 'Spacious pockets', 'Adjustable hood'],
    stock: 145,
    stockStatus: 'in-stock',
    badge: 'bestseller',
    rating: 4.8,
    reviewCount: 2876,
    slug: 'classic-pullover-hoodie-unisex',
  },
  {
    id: 'hood-002',
    name: 'Zip-Up Tech Hoodie',
    category: 'clothing',
    subcategory: 'hoodies',
    price: 99,
    description: 'Advanced zip-up hoodie with performance fabric',
    longDescription: 'Zip-Up Tech combines technology with style. Moisture-wicking, breathable, and perfect for active use.',
    images: [
      'https://images.unsplash.com/photo-1556821552-7f41c5d440db?w=800&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1556821552-7f41c5d440db?w=200&h=200&fit=crop',
    gender: 'men',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Black', hex: '#000000', sku: 'HOOD-TECH-BLK' },
      { name: 'Gray', hex: '#A9A9A9', sku: 'HOOD-TECH-GRY' },
      { name: 'Blue', hex: '#0066CC', sku: 'HOOD-TECH-BLU' },
    ],
    material: '88% polyester, 12% spandex',
    details: ['Zip-up style', 'Performance fabric', 'Breathable'],
    features: ['Moisture-wicking', 'Four-way stretch', 'Thumb holes', 'Reflective details'],
    stock: 98,
    stockStatus: 'in-stock',
    badge: 'new',
    discount: 10,
    rating: 4.7,
    reviewCount: 1645,
    slug: 'zip-up-tech-hoodie-men',
  },

  // ========== CLOTHING: JOGGING/PANTS (3 products) ==========
  {
    id: 'pant-001',
    name: 'Performance Jogger',
    category: 'clothing',
    subcategory: 'jogging',
    price: 79,
    description: 'Versatile jogger for sport and casual wear',
    longDescription: 'Performance Jogger blends comfort with style. Perfect for workouts, casual outings, or relaxation.',
    images: [
      'https://images.unsplash.com/photo-1542272604-787c62d465d1?w=800&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1542272604-787c62d465d1?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Black', hex: '#000000', sku: 'JOG-PERF-BLK' },
      { name: 'Gray', hex: '#808080', sku: 'JOG-PERF-GRY' },
      { name: 'Navy', hex: '#001f3f', sku: 'JOG-PERF-NVY' },
    ],
    material: '70% cotton, 30% polyester',
    details: ['Tapered fit', 'Elastic waistband', 'Cuffed ankle'],
    features: ['Comfortable', 'Versatile', 'Breathable', 'Machine washable'],
    stock: 189,
    stockStatus: 'in-stock',
    badge: 'bestseller',
    rating: 4.7,
    reviewCount: 2134,
    slug: 'performance-jogger-unisex',
  },

  // ========== CLOTHING: JACKETS (2 products) ==========
  {
    id: 'jacket-001',
    name: 'Windbreaker Jacket',
    category: 'clothing',
    subcategory: 'jackets',
    price: 129,
    description: 'Lightweight windproof jacket',
    longDescription: 'Windbreaker Jacket protects from the elements. Packable, breathable, and perfect for outdoor activities.',
    images: [
      'https://images.unsplash.com/photo-1551028719-00167b16ebc5?w=800&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1551028719-00167b16ebc5?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Black', hex: '#000000', sku: 'WIND-JAC-BLK' },
      { name: 'Blue', hex: '#0066CC', sku: 'WIND-JAC-BLU' },
      { name: 'Red', hex: '#FF0000', sku: 'WIND-JAC-RED' },
    ],
    material: '100% nylon, waterproof coating',
    details: ['Lightweight', 'Packable', 'Waterproof'],
    features: ['Wind-resistant', 'Packable design', 'Adjustable hood', 'Breathable'],
    stock: 123,
    stockStatus: 'in-stock',
    badge: 'bestseller',
    discount: 15,
    rating: 4.7,
    reviewCount: 1876,
    slug: 'windbreaker-jacket-unisex',
  },

  // ========== ACCESSORIES (5 products) ==========
  {
    id: 'acc-sock-001',
    name: 'Cushioned Sports Socks (3-Pack)',
    category: 'accessories',
    subcategory: 'socks',
    price: 24,
    description: 'Triple pack of cushioned sports socks',
    longDescription: 'Comfort meets performance. Cushioned Sports Socks provide support and breathability for active feet.',
    images: [
      'https://images.unsplash.com/photo-1567186137166-a5cba73e7b97?w=800&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1567186137166-a5cba73e7b97?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['One Size'],
    colors: [
      { name: 'Black', hex: '#000000', sku: 'SOCK-CUSH-BLK' },
      { name: 'White', hex: '#FFFFFF', sku: 'SOCK-CUSH-WHT' },
      { name: 'Multi', hex: '#999999', sku: 'SOCK-CUSH-MUL' },
    ],
    material: '70% cotton, 25% polyester, 5% spandex',
    details: ['3-pack bundle', 'Cushioned sole'],
    features: ['Comfortable', 'Durable', 'Moisture-wicking', 'All-day wear'],
    stock: 345,
    stockStatus: 'in-stock',
    badge: 'bestseller',
    rating: 4.5,
    reviewCount: 2156,
    slug: 'cushioned-sports-socks-3pack',
  },
  {
    id: 'acc-cap-001',
    name: 'Classic Baseball Cap',
    category: 'accessories',
    subcategory: 'caps',
    price: 35,
    description: 'Timeless baseball cap',
    longDescription: 'Classic Baseball Cap is perfect for sun protection and casual style. Adjustable fit for all head sizes.',
    images: [
      'https://images.unsplash.com/photo-1612528443702-f6741f70a049?w=800&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1612528443702-f6741f70a049?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['One Size'],
    colors: [
      { name: 'Black', hex: '#000000', sku: 'CAP-BALL-BLK' },
      { name: 'White', hex: '#FFFFFF', sku: 'CAP-BALL-WHT' },
      { name: 'Navy', hex: '#001f3f', sku: 'CAP-BALL-NVY' },
      { name: 'Red', hex: '#FF0000', sku: 'CAP-BALL-RED' },
    ],
    material: '100% cotton twill',
    details: ['Adjustable strap', 'Curved bill'],
    features: ['UV protection', 'Comfortable', 'Versatile', 'Easy care'],
    stock: 267,
    stockStatus: 'in-stock',
    rating: 4.4,
    reviewCount: 1342,
    slug: 'classic-baseball-cap',
  },
  {
    id: 'acc-bag-001',
    name: 'Sport Backpack',
    category: 'accessories',
    subcategory: 'bags',
    price: 79,
    description: 'Durable backpack for sports and travel',
    longDescription: 'Sport Backpack features multiple compartments, comfortable straps, and water-resistant material. Perfect for gym or daily commute.',
    images: [
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['One Size'],
    colors: [
      { name: 'Black', hex: '#000000', sku: 'BAG-SPORT-BLK' },
      { name: 'Gray', hex: '#808080', sku: 'BAG-SPORT-GRY' },
      { name: 'Navy', hex: '#001f3f', sku: 'BAG-SPORT-NVY' },
    ],
    material: 'Water-resistant nylon',
    details: ['Laptop compartment', '30L capacity', 'Adjustable straps'],
    features: ['Water-resistant', 'Spacious', 'Comfortable', 'Durable'],
    stock: 156,
    stockStatus: 'in-stock',
    badge: 'bestseller',
    rating: 4.6,
    reviewCount: 1876,
    slug: 'sport-backpack',
  },

  // ========== EQUIPMENT (5 products) ==========
  {
    id: 'equip-001',
    name: 'Jump Rope Pro',
    category: 'equipment',
    subcategory: 'training',
    price: 35,
    description: 'Professional jump rope for cardio training',
    longDescription: 'Jump Rope Pro features ball bearings for smooth rotation and an ergonomic handle. Perfect for box training and cardio.',
    images: [
      'https://images.unsplash.com/photo-1574281066162-7a0fb31e8b07?w=800&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1574281066162-7a0fb31e8b07?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['One Size'],
    colors: [
      { name: 'Black', hex: '#000000', sku: 'JUMP-ROPE-BLK' },
      { name: 'Red', hex: '#FF0000', sku: 'JUMP-ROPE-RED' },
    ],
    material: 'Steel wire, foam handles',
    details: ['Adjustable length', 'Ball bearings', 'Professional grade'],
    features: ['Smooth rotation', 'Durable', 'Lightweight', 'Portable'],
    stock: 89,
    stockStatus: 'in-stock',
    rating: 4.7,
    reviewCount: 567,
    slug: 'jump-rope-pro',
  },
  {
    id: 'equip-002',
    name: 'Resistance Band Set (5-pack)',
    category: 'equipment',
    subcategory: 'training',
    price: 45,
    description: 'Multi-level resistance bands for home and gym training',
    longDescription: 'Resistance Band Set includes 5 different resistance levels. Perfect for strength training, physical therapy, and toning.',
    images: [
      'https://images.unsplash.com/photo-1517836357463-d25ddfcbf042?w=800&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1517836357463-d25ddfcbf042?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['One Size'],
    colors: [
      { name: 'Multi-Color', hex: '#FF6B6B', sku: 'RES-BAND-MUL' },
    ],
    material: 'Natural latex',
    details: ['5 resistance levels', 'Portable', 'Durable'],
    features: ['Home gym essential', 'Versatile', 'Durable', 'Affordable'],
    stock: 134,
    stockStatus: 'in-stock',
    badge: 'bestseller',
    rating: 4.8,
    reviewCount: 1243,
    slug: 'resistance-band-set-5pack',
  },
  {
    id: 'equip-003',
    name: 'Water Bottle 1L',
    category: 'equipment',
    subcategory: 'hydration',
    price: 28,
    description: 'Insulated stainless steel water bottle',
    longDescription: 'Water Bottle keeps drinks cold for 24 hours or hot for 12 hours. Lightweight and durable for any activity.',
    images: [
      'https://images.unsplash.com/photo-1602088113235-229c19758e9f?w=800&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1602088113235-229c19758e9f?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['One Size'],
    colors: [
      { name: 'Black', hex: '#000000', sku: 'WATER-BOT-BLK' },
      { name: 'White', hex: '#FFFFFF', sku: 'WATER-BOT-WHT' },
      { name: 'Blue', hex: '#0066CC', sku: 'WATER-BOT-BLU' },
      { name: 'Red', hex: '#FF0000', sku: 'WATER-BOT-RED' },
    ],
    material: 'Stainless steel',
    details: ['Double-wall insulation', '1L capacity', 'Leak-proof'],
    features: ['Temperature control', 'Lightweight', 'Eco-friendly', 'Durable'],
    stock: 267,
    stockStatus: 'in-stock',
    badge: 'new',
    rating: 4.9,
    reviewCount: 2341,
    slug: 'water-bottle-1l',
  },
]
