export interface Product {
  id: string
  name: string
  category: 'shoes' | 'clothing' | 'accessories' | 'equipment'
  subcategory: string
  price: number
  originalPrice?: number
  description: string
  longDescription: string
  images: string[]
  thumbnail: string
  gender: 'men' | 'women' | 'unisex'

  sizes: string[]
  sizeChart?: string

  colors: { name: string; hex: string; sku: string }[]

  material: string
  details: string[]
  features: string[]

  stock: number
  stockStatus: 'in-stock' | 'low-stock' | 'pre-order' | 'out-of-stock'

  discount?: number
  badge?: 'new' | 'bestseller' | 'sale' | 'limited'

  rating: number
  reviewCount: number

  slug: string
}

export const products: Product[] = [
  // ========== SHOES: RUNNING (10 products) ==========
  {
    id: 'shoe-run-001',
    name: 'Velocity Pro Max',
    category: 'shoes',
    subcategory: 'running',
    price: 189,
    description: 'Ultra-lightweight running shoe with responsive foam cushioning',
    longDescription: 'Experience maximum performance with the Velocity Pro Max. Engineered for speed with responsive Quantum foam, breathable mesh upper, and durable rubber outsole. Perfect for road running and track.',
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1460353581641-a1af1d3ba3c1?w=800&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=200&h=200&fit=crop',
    gender: 'men',
    sizes: ['35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46'],
    colors: [
      { name: 'Black', hex: '#000000', sku: 'VEL-PRO-BLK' },
      { name: 'White', hex: '#FFFFFF', sku: 'VEL-PRO-WHT' },
      { name: 'Navy', hex: '#001f3f', sku: 'VEL-PRO-NVY' },
      { name: 'Red', hex: '#FF4136', sku: 'VEL-PRO-RED' },
    ],
    material: 'Mesh upper, foam midsole, rubber outsole',
    details: ['Weight: 220g', 'Drop: 10mm', 'Cushioning: Quantum Foam'],
    features: ['Breathable mesh', 'Responsive cushioning', 'Durable traction', 'Lightweight design'],
    stock: 45,
    stockStatus: 'in-stock',
    discount: 15,
    badge: 'bestseller',
    rating: 4.8,
    reviewCount: 1203,
    slug: 'velocity-pro-max-men',
  },
  {
    id: 'shoe-run-002',
    name: 'Quantum Flow Runner',
    category: 'shoes',
    subcategory: 'running',
    price: 159,
    description: 'Lightweight and responsive running shoe for everyday training',
    longDescription: 'The Quantum Flow offers the perfect balance of comfort and responsiveness. With advanced cushioning and a secure fit, this shoe excels on both short runs and long distances.',
    images: [
      'https://images.unsplash.com/photo-1549622328-ace0f0cc2eb4?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1549622328-ace0f0cc2eb4?w=200&h=200&fit=crop',
    gender: 'women',
    sizes: ['34', '35', '36', '37', '38', '39', '40', '41', '42', '43'],
    colors: [
      { name: 'Purple', hex: '#9933CC', sku: 'QF-RUN-PUR' },
      { name: 'Gray', hex: '#999999', sku: 'QF-RUN-GRY' },
      { name: 'Pink', hex: '#FF69B4', sku: 'QF-RUN-PNK' },
      { name: 'Black', hex: '#000000', sku: 'QF-RUN-BLK' },
    ],
    material: 'Engineered mesh, cushioning foam, rubber outsole',
    details: ['Weight: 215g', 'Drop: 8mm', "Women's fit"],
    features: ['Anatomical design', 'Responsive feel', 'Breathable upper', 'Eco-friendly materials'],
    stock: 62,
    stockStatus: 'in-stock',
    badge: 'new',
    rating: 4.7,
    reviewCount: 856,
    slug: 'quantum-flow-runner-women',
  },
  {
    id: 'shoe-run-003',
    name: 'Aeromesh Lite',
    category: 'shoes',
    subcategory: 'running',
    price: 99,
    description: 'Budget-friendly running shoe without compromising quality',
    longDescription: 'The Aeromesh Lite proves that performance doesn\'t have to be expensive. With a lightweight mesh upper and reliable cushioning, it\'s perfect for casual runners.',
    images: [
      'https://images.unsplash.com/photo-1533635798891-2e2e00c326a6?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1533635798891-2e2e00c326a6?w=200&h=200&fit=crop',
    gender: 'men',
    sizes: ['36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46'],
    colors: [
      { name: 'Gray', hex: '#808080', sku: 'AML-GRY' },
      { name: 'Blue', hex: '#0066CC', sku: 'AML-BLU' },
      { name: 'White', hex: '#FFFFFF', sku: 'AML-WHT' },
    ],
    material: 'Mesh upper, EVA foam, rubber outsole',
    details: ['Weight: 235g', 'Drop: 10mm', 'Entry-level'],
    features: ['Breathable', 'Comfortable fit', 'Affordable', 'Durable'],
    stock: 78,
    stockStatus: 'in-stock',
    rating: 4.5,
    reviewCount: 542,
    slug: 'aeromesh-lite-men',
  },
  {
    id: 'shoe-run-004',
    name: 'TrailBlazer X Outdoor',
    category: 'shoes',
    subcategory: 'running',
    price: 175,
    description: 'Trail running shoe with aggressive tread for off-road performance',
    longDescription: 'Conquer any terrain with the TrailBlazer X. Featuring reinforced sides, protective toe cap, and aggressive outsole pattern for maximum grip on trails.',
    images: [
      'https://images.unsplash.com/photo-1605348532760-6233dd1d191e?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1605348532760-6233dd1d191e?w=200&h=200&fit=crop',
    gender: 'women',
    sizes: ['34', '35', '36', '37', '38', '39', '40', '41', '42'],
    colors: [
      { name: 'Green', hex: '#228B22', sku: 'TRX-GRN' },
      { name: 'Orange', hex: '#FF8C00', sku: 'TRX-ORG' },
      { name: 'Black', hex: '#000000', sku: 'TRX-BLK' },
    ],
    material: 'Trail mesh, protective TPU, aggressive rubber',
    details: ['Weight: 280g', 'Drop: 10mm', 'Trail-specific'],
    features: ['Protective toe cap', 'Aggressive tread', 'Rock plate', 'Ankle support'],
    stock: 34,
    stockStatus: 'low-stock',
    badge: 'new',
    rating: 4.6,
    reviewCount: 423,
    slug: 'trailblazer-x-outdoor-women',
  },
  {
    id: 'shoe-run-005',
    name: 'Endurance Beast 2.0',
    category: 'shoes',
    subcategory: 'running',
    price: 199,
    description: 'Maximum cushioning for ultra-distance running events',
    longDescription: 'Designed for marathoners and ultra-runners. The Endurance Beast 2.0 features maximum cushioning and a wider base for stability during long distances.',
    images: [
      'https://images.unsplash.com/photo-1551958219-acbc608c6be4?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1551958219-acbc608c6be4?w=200&h=200&fit=crop',
    gender: 'men',
    sizes: ['36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46'],
    colors: [
      { name: 'Black', hex: '#000000', sku: 'EB20-BLK' },
      { name: 'White', hex: '#FFFFFF', sku: 'EB20-WHT' },
      { name: 'Blue', hex: '#0066CC', sku: 'EB20-BLU' },
    ],
    material: 'Max cushioning foam, breathable mesh, durable rubber',
    details: ['Weight: 310g', 'Drop: 10mm', 'Ultra-cushioned'],
    features: ['Maximum cushioning', 'Wide base', 'Stable ride', 'Distance-focused'],
    stock: 28,
    stockStatus: 'in-stock',
    badge: 'bestseller',
    rating: 4.7,
    reviewCount: 789,
    slug: 'endurance-beast-2-0-men',
  },
  {
    id: 'shoe-run-006',
    name: 'Swift Pro Runner',
    category: 'shoes',
    subcategory: 'running',
    price: 145,
    description: 'Speed-focused minimalist running shoe',
    longDescription: 'The Swift Pro is built for speed. Its minimal design and lightweight construction make it perfect for interval training and tempo runs.',
    images: [
      'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=200&h=200&fit=crop',
    gender: 'women',
    sizes: ['34', '35', '36', '37', '38', '39', '40', '41', '42', '43'],
    colors: [
      { name: 'White', hex: '#FFFFFF', sku: 'SWF-WHT' },
      { name: 'Pink', hex: '#FF1493', sku: 'SWF-PNK' },
      { name: 'Black', hex: '#000000', sku: 'SWF-BLK' },
    ],
    material: 'Lightweight mesh, minimal foam, racing rubber',
    details: ['Weight: 185g', 'Drop: 8mm', 'Minimalist design'],
    features: ['Lightweight', 'Responsive', 'Racing flat', 'Comfortable toe box'],
    stock: 51,
    stockStatus: 'in-stock',
    rating: 4.4,
    reviewCount: 367,
    slug: 'swift-pro-runner-women',
  },
  {
    id: 'shoe-run-007',
    name: 'Storm Runner Pro',
    category: 'shoes',
    subcategory: 'running',
    price: 179,
    description: 'Weather-resistant running shoe for all conditions',
    longDescription: 'Built to handle any weather. The Storm Runner features water-resistant materials and enhanced grip for safe running in wet conditions.',
    images: [
      'https://images.unsplash.com/photo-1552820728-8ac41f1ce891?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1552820728-8ac41f1ce891?w=200&h=200&fit=crop',
    gender: 'men',
    sizes: ['36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46'],
    colors: [
      { name: 'Gray', hex: '#707070', sku: 'SRM-GRY' },
      { name: 'Navy', hex: '#001f3f', sku: 'SRM-NVY' },
    ],
    material: 'Water-resistant mesh, protective coating, aggressive tread',
    details: ['Weight: 250g', 'Drop: 10mm', 'Water-resistant'],
    features: ['Water-resistant', 'All-weather', 'Enhanced grip', 'Reflective elements'],
    stock: 38,
    stockStatus: 'in-stock',
    rating: 4.5,
    reviewCount: 445,
    slug: 'storm-runner-pro-men',
  },
  {
    id: 'shoe-run-008',
    name: 'Momentum Elite',
    category: 'shoes',
    subcategory: 'running',
    price: 189,
    description: 'Premium running shoe with advanced technology',
    longDescription: 'The Momentum Elite combines cutting-edge cushioning technology with elegant design. Perfect for runners who demand the best.',
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1460353581641-a1af1d3ba3c1?w=800&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=200&h=200&fit=crop',
    gender: 'women',
    sizes: ['34', '35', '36', '37', '38', '39', '40', '41', '42', '43'],
    colors: [
      { name: 'Black', hex: '#000000', sku: 'MMT-BLK' },
      { name: 'Rose Gold', hex: '#B76E79', sku: 'MMT-RG' },
    ],
    material: 'Premium mesh, advanced foam, premium rubber',
    details: ['Weight: 225g', 'Drop: 10mm', 'Premium build'],
    features: ['Premium materials', 'Advanced cushioning', 'Sleek design', 'Long-lasting'],
    stock: 42,
    stockStatus: 'in-stock',
    badge: 'new',
    rating: 4.8,
    reviewCount: 512,
    slug: 'momentum-elite-women',
  },
  {
    id: 'shoe-run-009',
    name: 'Sprint Velocity',
    category: 'shoes',
    subcategory: 'running',
    price: 129,
    description: 'Lightweight sprint shoe for track workouts',
    longDescription: 'Designed for sprinters and track athletes. The Sprint Velocity offers minimal weight and maximum speed for short, explosive runs.',
    images: [
      'https://images.unsplash.com/photo-1533634026-e0953c89dd0d?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1533634026-e0953c89dd0d?w=200&h=200&fit=crop',
    gender: 'men',
    sizes: ['36', '37', '38', '39', '40', '41', '42', '43', '44', '45'],
    colors: [
      { name: 'Yellow', hex: '#FFD700', sku: 'SPR-YEL' },
      { name: 'Black', hex: '#000000', sku: 'SPR-BLK' },
    ],
    material: 'Mesh upper, minimal foam, track rubber',
    details: ['Weight: 170g', 'Drop: 7mm', 'Track spike-compatible'],
    features: ['Ultra-lightweight', 'Minimal cushioning', 'Track focused', 'Breathable'],
    stock: 25,
    stockStatus: 'low-stock',
    rating: 4.3,
    reviewCount: 289,
    slug: 'sprint-velocity-men',
  },
  {
    id: 'shoe-run-010',
    name: 'Comfort Cruiser',
    category: 'shoes',
    subcategory: 'running',
    price: 119,
    description: 'Comfortable running shoe for casual training',
    longDescription: 'For those who value comfort above all. The Comfort Cruiser is perfect for leisurely jogs and casual running with excellent support.',
    images: [
      'https://images.unsplash.com/photo-1545291026-7e4e2fb6b25b?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1545291026-7e4e2fb6b25b?w=200&h=200&fit=crop',
    gender: 'women',
    sizes: ['34', '35', '36', '37', '38', '39', '40', '41', '42', '43'],
    colors: [
      { name: 'Beige', hex: '#F5F5DC', sku: 'CRZ-BEI' },
      { name: 'Gray', hex: '#A9A9A9', sku: 'CRZ-GRY' },
      { name: 'Black', hex: '#000000', sku: 'CRZ-BLK' },
    ],
    material: 'Comfort mesh, soft foam, flexible rubber',
    details: ['Weight: 270g', 'Drop: 10mm', 'Comfort-focused'],
    features: ['Maximum comfort', 'Soft cushioning', 'Easy fit', 'Perfect for beginners'],
    stock: 89,
    stockStatus: 'in-stock',
    rating: 4.6,
    reviewCount: 723,
    slug: 'comfort-cruiser-women',
  },

  // ========== SHOES: BASKETBALL (2 products) ==========
  {
    id: 'shoe-bask-001',
    name: 'Air Jordan Elite',
    category: 'shoes',
    subcategory: 'basketball',
    price: 229,
    description: 'Premium basketball shoe inspired by legendary design',
    longDescription: 'Inspired by basketball legends. The Air Jordan Elite combines style, comfort, and performance for on-court dominance.',
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1460353581641-a1af1d3ba3c1?w=800&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=200&h=200&fit=crop',
    gender: 'men',
    sizes: ['36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46'],
    colors: [
      { name: 'Black/Red', hex: '#000000', sku: 'AIR-BRD' },
      { name: 'White/Gold', hex: '#FFFFFF', sku: 'AIR-WG' },
    ],
    material: 'Synthetic leather, foam midsole, rubber outsole',
    details: ['Weight: 320g', 'Drop: 12mm', 'Basketball-specific'],
    features: ['Ankle support', 'Responsive bounce', 'Durable leather', 'Classic design'],
    stock: 18,
    stockStatus: 'in-stock',
    badge: 'bestseller',
    rating: 4.9,
    reviewCount: 1456,
    slug: 'air-jordan-elite-men',
  },
  {
    id: 'shoe-bask-002',
    name: 'Court Master Pro',
    category: 'shoes',
    subcategory: 'basketball',
    price: 169,
    description: 'Performance basketball shoe with enhanced stability',
    longDescription: 'Engineered for court performance. Court Master Pro offers superior ankle support and traction for competitive play.',
    images: [
      'https://images.unsplash.com/photo-1605348532760-6233dd1d191e?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1605348532760-6233dd1d191e?w=200&h=200&fit=crop',
    gender: 'women',
    sizes: ['34', '35', '36', '37', '38', '39', '40', '41', '42'],
    colors: [
      { name: 'Purple', hex: '#800080', sku: 'CMP-PUR' },
      { name: 'Blue', hex: '#0066CC', sku: 'CMP-BLU' },
    ],
    material: 'Mesh/synthetic blend, responsive foam, court rubber',
    details: ['Weight: 310g', 'Drop: 10mm', "Women's performance fit"],
    features: ['Enhanced stability', 'Court grip', 'Lightweight', 'Responsive feel'],
    stock: 32,
    stockStatus: 'in-stock',
    rating: 4.7,
    reviewCount: 634,
    slug: 'court-master-pro-women',
  },

  // ========== SHOES: CASUAL/LIFESTYLE (1 product) ==========
  {
    id: 'shoe-casual-001',
    name: 'Urban Sneaker Classic',
    category: 'shoes',
    subcategory: 'lifestyle',
    price: 89,
    description: 'Versatile sneaker for everyday style and comfort',
    longDescription: 'The perfect everyday sneaker. The Urban Sneaker Classic combines timeless design with modern comfort technology.',
    images: [
      'https://images.unsplash.com/photo-1517836357463-d25ddfcbf042?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1517836357463-d25ddfcbf042?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45'],
    colors: [
      { name: 'White', hex: '#FFFFFF', sku: 'URB-WHT' },
      { name: 'Black', hex: '#000000', sku: 'URB-BLK' },
      { name: 'Gray', hex: '#808080', sku: 'URB-GRY' },
    ],
    material: 'Canvas upper, rubber sole, cotton lining',
    details: ['Weight: 240g', 'Drop: 15mm', 'Unisex sizing'],
    features: ['Classic design', 'All-day comfort', 'Durable canvas', 'Easy maintenance'],
    stock: 124,
    stockStatus: 'in-stock',
    badge: 'bestseller',
    rating: 4.8,
    reviewCount: 2103,
    slug: 'urban-sneaker-classic-unisex',
  },

  // ========== CLOTHING: T-SHIRTS (5 products) ==========
  {
    id: 'cloth-tee-001',
    name: 'Essential Crew Neck Tee',
    category: 'clothing',
    subcategory: 't-shirt',
    price: 29,
    description: 'Classic cotton t-shirt for everyday wear',
    longDescription: 'The foundation of any wardrobe. Our Essential Crew Neck Tee is made from premium cotton and available in a range of colors.',
    images: [
      'https://images.unsplash.com/photo-1501746074465-4cebaf45b800?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1542272604-787c62d465d1?w=800&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1501746074465-4cebaf45b800?w=200&h=200&fit=crop',
    gender: 'men',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'White', hex: '#FFFFFF', sku: 'ESS-WHT' },
      { name: 'Black', hex: '#000000', sku: 'ESS-BLK' },
      { name: 'Gray', hex: '#808080', sku: 'ESS-GRY' },
      { name: 'Navy', hex: '#001f3f', sku: 'ESS-NVY' },
    ],
    material: '100% cotton, preshrunk, comfortable fit',
    details: ['GSM: 150', 'Fit: Regular', 'Weight: 150g per piece'],
    features: ['Soft cotton', 'Everyday wear', 'Easy care', 'Classic cut'],
    stock: 156,
    stockStatus: 'in-stock',
    badge: 'bestseller',
    rating: 4.7,
    reviewCount: 3245,
    slug: 'essential-crew-neck-tee-men',
  },
  {
    id: 'cloth-tee-002',
    name: 'Performance Moisture-Wicking Tee',
    category: 'clothing',
    subcategory: 't-shirt',
    price: 49,
    description: 'Athletic t-shirt with advanced moisture-wicking technology',
    longDescription: 'Built for performance. This t-shirt keeps you dry during intense workouts with advanced moisture-wicking fabric.',
    images: [
      'https://images.unsplash.com/photo-1502716671518-7bec82b148bb?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1542272604-787c62d465d1?w=800&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1502716671518-7bec82b148bb?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Black', hex: '#000000', sku: 'PERF-BLK' },
      { name: 'White', hex: '#FFFFFF', sku: 'PERF-WHT' },
      { name: 'Neon', hex: '#00FF00', sku: 'PERF-NEO' },
    ],
    material: '88% polyester, 12% spandex, moisture-wicking',
    details: ['GSM: 140', 'Fit: Slim', 'Breathable fabric'],
    features: ['Moisture-wicking', 'Breathable', 'Stretch fabric', 'Quick-dry'],
    stock: 87,
    stockStatus: 'in-stock',
    badge: 'new',
    rating: 4.6,
    reviewCount: 1823,
    slug: 'performance-moisture-wicking-tee-unisex',
  },
  {
    id: 'cloth-tee-003',
    name: 'Essentials Oversized Tee',
    category: 'clothing',
    subcategory: 't-shirt',
    price: 39,
    description: 'Trendy oversized t-shirt for a relaxed look',
    longDescription: 'The oversized fit is back. This tee offers ultimate comfort with a contemporary oversized silhouette.',
    images: [
      'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1542272604-787c62d465d1?w=800&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=200&h=200&fit=crop',
    gender: 'women',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Cream', hex: '#FFFDD0', sku: 'OVER-CRM' },
      { name: 'Black', hex: '#000000', sku: 'OVER-BLK' },
      { name: 'Sage', hex: '#9DC183', sku: 'OVER-SAG' },
    ],
    material: '100% organic cotton, soft feel',
    details: ['GSM: 160', 'Fit: Oversized', 'Eco-friendly'],
    features: ['Organic cotton', 'Oversized fit', 'Soft texture', 'Sustainable'],
    stock: 94,
    stockStatus: 'in-stock',
    rating: 4.5,
    reviewCount: 1567,
    slug: 'essentials-oversized-tee-women',
  },
  {
    id: 'cloth-tee-004',
    name: 'Vintage Graphic Tee',
    category: 'clothing',
    subcategory: 't-shirt',
    price: 44,
    description: 'Classic graphic t-shirt with retro design',
    longDescription: 'Make a statement with our Vintage Graphic Tee. Featuring timeless retro graphics and premium construction.',
    images: [
      'https://images.unsplash.com/photo-1553535092-d7c37210b330?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1542272604-787c62d465d1?w=800&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1553535092-d7c37210b330?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Black', hex: '#000000', sku: 'GRPH-BLK' },
      { name: 'Heather', hex: '#B0B0B0', sku: 'GRPH-HEA' },
      { name: 'Navy', hex: '#001f3f', sku: 'GRPH-NVY' },
    ],
    material: '100% cotton, vintage print, premium quality',
    details: ['GSM: 155', 'Print: Vintage graphics', 'Fade-resistant'],
    features: ['Graphic design', 'Vintage aesthetic', 'Comfortable fit', 'Durable print'],
    stock: 63,
    stockStatus: 'in-stock',
    badge: 'new',
    rating: 4.4,
    reviewCount: 892,
    slug: 'vintage-graphic-tee-unisex',
  },
  {
    id: 'cloth-tee-005',
    name: 'Premium Tech Tee',
    category: 'clothing',
    subcategory: 't-shirt',
    price: 59,
    description: 'Advanced tech t-shirt with antimicrobial properties',
    longDescription: 'The future of t-shirts. Our Premium Tech Tee features antimicrobial fabric that stays fresher longer.',
    images: [
      'https://images.unsplash.com/photo-1516826957519-c21cc028cb29?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1542272604-787c62d465d1?w=800&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1516826957519-c21cc028cb29?w=200&h=200&fit=crop',
    gender: 'men',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Black', hex: '#000000', sku: 'TECH-BLK' },
      { name: 'White', hex: '#FFFFFF', sku: 'TECH-WHT' },
      { name: 'Navy', hex: '#001f3f', sku: 'TECH-NVY' },
    ],
    material: '85% polyester, 15% spandex, antimicrobial treatment',
    details: ['GSM: 145', 'Technology: Antimicrobial', 'Odor-resistant'],
    features: ['Antimicrobial', 'Odor-resistant', 'Breathable', 'Premium feel'],
    stock: 45,
    stockStatus: 'in-stock',
    badge: 'new',
    rating: 4.8,
    reviewCount: 456,
    slug: 'premium-tech-tee-men',
  },

  // ========== CLOTHING: HOODIES (2 products) ==========
  {
    id: 'cloth-hood-001',
    name: 'Classic Hoodie Sweatshirt',
    category: 'clothing',
    subcategory: 'hoodie',
    price: 89,
    description: 'Cozy classic hoodie for everyday comfort',
    longDescription: 'The perfect layering piece. Our Classic Hoodie is made from soft fleece and features a spacious kangaroo pocket.',
    images: [
      'https://images.unsplash.com/photo-1556821552-7f41c5d440db?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1556821552-7f41c5d440db?w=800&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1556821552-7f41c5d440db?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Black', hex: '#000000', sku: 'HOOD-BLK' },
      { name: 'Gray', hex: '#808080', sku: 'HOOD-GRY' },
      { name: 'Navy', hex: '#001f3f', sku: 'HOOD-NVY' },
      { name: 'White', hex: '#FFFFFF', sku: 'HOOD-WHT' },
    ],
    material: '80% cotton, 20% polyester fleece, soft lining',
    details: ['GSM: 280', 'Fit: Regular', 'Warm and cozy'],
    features: ['Soft fleece', 'Kangaroo pocket', 'Drawstring hood', 'Comfortable fit'],
    stock: 72,
    stockStatus: 'in-stock',
    badge: 'bestseller',
    rating: 4.8,
    reviewCount: 2567,
    slug: 'classic-hoodie-sweatshirt-unisex',
  },
  {
    id: 'cloth-hood-002',
    name: 'Performance Hoodie',
    category: 'clothing',
    subcategory: 'hoodie',
    price: 109,
    description: 'Athletic hoodie with moisture-wicking technology',
    longDescription: 'Engineered for performance. The Performance Hoodie keeps you dry during and after workouts.',
    images: [
      'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1556821552-7f41c5d440db?w=800&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=200&h=200&fit=crop',
    gender: 'women',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Black', hex: '#000000', sku: 'PERF-HOOD-BLK' },
      { name: 'Purple', hex: '#800080', sku: 'PERF-HOOD-PUR' },
    ],
    material: '88% polyester, 12% spandex, moisture-wicking',
    details: ['GSM: 240', 'Technology: Moisture-wicking', 'Lightweight'],
    features: ['Moisture-wicking', 'Lightweight', 'Stretchy', 'Quick-dry'],
    stock: 38,
    stockStatus: 'in-stock',
    rating: 4.6,
    reviewCount: 834,
    slug: 'performance-hoodie-women',
  },

  // ========== CLOTHING: JOGGING/PANTS (2 products) ==========
  {
    id: 'cloth-jog-001',
    name: 'Comfort Jogging Pants',
    category: 'clothing',
    subcategory: 'jogging',
    price: 69,
    description: 'Soft and comfortable jogging pants for relaxation',
    longDescription: 'Designed for ultimate comfort. These jogging pants are perfect for lounging, training, or casual outings.',
    images: [
      'https://images.unsplash.com/photo-1506629082632-81afc229d71d?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1506629082632-81afc229d71d?w=800&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1506629082632-81afc229d71d?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Black', hex: '#000000', sku: 'JOG-BLK' },
      { name: 'Gray', hex: '#808080', sku: 'JOG-GRY' },
      { name: 'Navy', hex: '#001f3f', sku: 'JOG-NVY' },
    ],
    material: '70% cotton, 30% polyester blend, soft fabric',
    details: ['Fit: Relaxed', 'Pockets: Yes', 'Drawstring: Adjustable'],
    features: ['Soft fabric', 'Comfortable fit', 'Side pockets', 'Breathable'],
    stock: 98,
    stockStatus: 'in-stock',
    badge: 'bestseller',
    rating: 4.7,
    reviewCount: 1945,
    slug: 'comfort-jogging-pants-unisex',
  },
  {
    id: 'cloth-jog-002',
    name: 'Pro Training Joggers',
    category: 'clothing',
    subcategory: 'jogging',
    price: 89,
    description: 'Professional training joggers with advanced features',
    longDescription: 'Built for serious athletes. These joggers feature tapered fit, reflective details, and moisture-wicking fabric.',
    images: [
      'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1506629082632-81afc229d71d?w=800&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=200&h=200&fit=crop',
    gender: 'men',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Black', hex: '#000000', sku: 'TRAIN-JOG-BLK' },
      { name: 'Navy', hex: '#001f3f', sku: 'TRAIN-JOG-NVY' },
    ],
    material: '85% polyester, 15% spandex, moisture-wicking',
    details: ['Fit: Tapered', 'Details: Reflective', 'Pockets: Deep side pockets'],
    features: ['Moisture-wicking', 'Tapered fit', 'Reflective details', 'Zippered ankles'],
    stock: 56,
    stockStatus: 'in-stock',
    rating: 4.5,
    reviewCount: 712,
    slug: 'pro-training-joggers-men',
  },

  // ========== CLOTHING: JACKETS (1 product) ==========
  {
    id: 'cloth-jack-001',
    name: 'Premium Track Jacket',
    category: 'clothing',
    subcategory: 'jacket',
    price: 129,
    description: 'Lightweight track jacket perfect for layering',
    longDescription: 'The versatile layering essential. Our Premium Track Jacket features a sleek design and practical pockets.',
    images: [
      'https://images.unsplash.com/photo-1544131519-66275a55f5ef?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1544131519-66275a55f5ef?w=800&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1544131519-66275a55f5ef?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Black', hex: '#000000', sku: 'TRACK-BLK' },
      { name: 'White', hex: '#FFFFFF', sku: 'TRACK-WHT' },
      { name: 'Navy', hex: '#001f3f', sku: 'TRACK-NVY' },
    ],
    material: '100% polyester, lightweight, water-resistant',
    details: ['Weight: 250g', 'Fit: Regular', 'Zippers: Full front'],
    features: ['Lightweight', 'Water-resistant', 'Zipped pockets', 'Breathable'],
    stock: 67,
    stockStatus: 'in-stock',
    badge: 'new',
    rating: 4.6,
    reviewCount: 523,
    slug: 'premium-track-jacket-unisex',
  },

  // ========== ACCESSORIES (3 products) ==========
  {
    id: 'acc-001',
    name: 'Premium Athletic Socks',
    category: 'accessories',
    subcategory: 'socks',
    price: 19,
    description: 'High-performance socks for all activities',
    longDescription: 'Keep your feet comfortable with our Premium Athletic Socks. Featuring arch support and moisture-wicking technology.',
    images: [
      'https://images.unsplash.com/photo-1586350977529-19106dd434c3?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1586350977529-19106dd434c3?w=800&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1586350977529-19106dd434c3?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['One Size'],
    colors: [
      { name: 'Black', hex: '#000000', sku: 'SOCK-BLK' },
      { name: 'White', hex: '#FFFFFF', sku: 'SOCK-WHT' },
    ],
    material: '85% nylon, 10% spandex, 5% polyester',
    details: ['Height: Crew', 'Cushioning: Medium', 'Arch support: Yes'],
    features: ['Arch support', 'Moisture-wicking', 'Durable', 'Comfortable fit'],
    stock: 234,
    stockStatus: 'in-stock',
    rating: 4.7,
    reviewCount: 1203,
    slug: 'premium-athletic-socks-unisex',
  },
  {
    id: 'acc-002',
    name: 'Classic Sports Cap',
    category: 'accessories',
    subcategory: 'cap',
    price: 39,
    description: 'Timeless sports cap for sun protection',
    longDescription: 'Simple yet stylish. Our Classic Sports Cap features a curved brim and adjustable back for the perfect fit.',
    images: [
      'https://images.unsplash.com/photo-1525863418897-7d66d28e5a30?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1525863418897-7d66d28e5a30?w=800&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1525863418897-7d66d28e5a30?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['One Size Fits Most'],
    colors: [
      { name: 'Black', hex: '#000000', sku: 'CAP-BLK' },
      { name: 'White', hex: '#FFFFFF', sku: 'CAP-WHT' },
      { name: 'Navy', hex: '#001f3f', sku: 'CAP-NVY' },
    ],
    material: '100% cotton, structured crown, curved brim',
    details: ['Fit: Adjustable', 'Style: Classic', 'Closure: Metal buckle'],
    features: ['UV protection', 'Adjustable fit', 'Durable cotton', 'Classic style'],
    stock: 156,
    stockStatus: 'in-stock',
    badge: 'bestseller',
    rating: 4.8,
    reviewCount: 892,
    slug: 'classic-sports-cap-unisex',
  },
  {
    id: 'acc-003',
    name: 'Sport Gym Backpack',
    category: 'accessories',
    subcategory: 'backpack',
    price: 79,
    description: 'Spacious backpack designed for gym and travel',
    longDescription: 'Your perfect gym companion. The Sport Gym Backpack features multiple compartments and ventilated shoe storage.',
    images: [
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['One Size'],
    colors: [
      { name: 'Black', hex: '#000000', sku: 'BAG-BLK' },
      { name: 'Gray', hex: '#808080', sku: 'BAG-GRY' },
    ],
    material: 'Water-resistant nylon, padded straps',
    details: ['Capacity: 35L', 'Compartments: 3', 'Shoe compartment: Yes'],
    features: ['Ventilated shoe storage', 'Multiple compartments', 'Padded straps', 'Water-resistant'],
    stock: 45,
    stockStatus: 'in-stock',
    rating: 4.6,
    reviewCount: 534,
    slug: 'sport-gym-backpack-unisex',
  },

  // ========== EQUIPMENT (3 products) ==========
  {
    id: 'equip-001',
    name: 'Professional Jump Rope',
    category: 'equipment',
    subcategory: 'cardio',
    price: 34,
    description: 'High-speed jump rope for intense cardio training',
    longDescription: 'Master your cardio with our Professional Jump Rope. Featuring ball bearings for smooth rotation and an ergonomic grip.',
    images: [
      'https://images.unsplash.com/photo-1599447988081-eb842a64311c?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1599447988081-eb842a64311c?w=800&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1599447988081-eb842a64311c?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['One Size'],
    colors: [
      { name: 'Black', hex: '#000000', sku: 'JR-BLK' },
      { name: 'Red', hex: '#FF0000', sku: 'JR-RED' },
    ],
    material: 'Steel cable, foam grip handles',
    details: ['Cable type: Steel', 'Ball bearings: Yes', 'Length: Adjustable'],
    features: ['Ball bearing rotation', 'Foam grip', 'Adjustable length', 'Durable steel'],
    stock: 78,
    stockStatus: 'in-stock',
    rating: 4.7,
    reviewCount: 456,
    slug: 'professional-jump-rope-unisex',
  },
  {
    id: 'equip-002',
    name: 'Resistance Band Set',
    category: 'equipment',
    subcategory: 'strength',
    price: 49,
    description: 'Complete resistance band set for home workouts',
    longDescription: 'Transform your training with our Resistance Band Set. Includes 5 bands with varying resistance levels and a carrying bag.',
    images: [
      'https://images.unsplash.com/photo-1517836357463-d25ddfcbf042?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1517836357463-d25ddfcbf042?w=800&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1517836357463-d25ddfcbf042?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['One Size'],
    colors: [
      { name: 'Multicolor', hex: '#FF0000', sku: 'RES-MULTI' },
    ],
    material: 'Latex-free rubber, eco-friendly',
    details: ['Bands included: 5', 'Resistance levels: 5', 'Carrying bag: Yes'],
    features: ['5 resistance levels', 'Latex-free', 'Eco-friendly', 'Portable bag'],
    stock: 65,
    stockStatus: 'in-stock',
    rating: 4.8,
    reviewCount: 723,
    slug: 'resistance-band-set-unisex',
  },
  {
    id: 'equip-003',
    name: 'Premium Water Bottle',
    category: 'equipment',
    subcategory: 'hydration',
    price: 32,
    description: 'Insulated water bottle for hot and cold beverages',
    longDescription: 'Stay hydrated in style. Our Premium Water Bottle keeps drinks cold for 24 hours or hot for 12 hours.',
    images: [
      'https://images.unsplash.com/photo-1602088113235-229c19758e9f?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1602088113235-229c19758e9f?w=800&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1602088113235-229c19758e9f?w=200&h=200&fit=crop',
    gender: 'unisex',
    sizes: ['750ml', '1000ml'],
    colors: [
      { name: 'Black', hex: '#000000', sku: 'WATER-BLK' },
      { name: 'White', hex: '#FFFFFF', sku: 'WATER-WHT' },
      { name: 'Navy', hex: '#001f3f', sku: 'WATER-NVY' },
    ],
    material: 'Stainless steel, double-wall insulated',
    details: ['Capacity: 750ml/1000ml', 'Insulation: 24hr cold', 'Material: Stainless steel'],
    features: ['Double-wall insulated', 'Keeps cold 24hrs', 'Keeps hot 12hrs', 'Leak-proof'],
    stock: 112,
    stockStatus: 'in-stock',
    badge: 'bestseller',
    rating: 4.9,
    reviewCount: 1834,
    slug: 'premium-water-bottle-unisex',
  },
]
